import type { ImportSchemaConfig } from '../../../components/import/types';

export const attendanceImportSchema: ImportSchemaConfig = {
  entityTitle: 'Biometric & Shift Attendance Logs',
  templateFileName: 'erp_attendance_import_template',
  uniqueIdentifierKey: 'employee_code',
  supportsUpsert: true,
  apiEndpoint: '/hr/attendances/bulk-import',
  columns: [
    {
      key: 'employee_code',
      label: 'Employee Code',
      required: true,
      type: 'string',
      sampleValue: 'EMP-00101',
      description: 'Employee badge or employee code in staff directory',
      aliases: ['employee_code', 'emp_code', 'code', 'staff_id', 'employee_id', 'badge_id'],
    },
    {
      key: 'attendance_date',
      label: 'Attendance Date',
      required: true,
      type: 'date',
      sampleValue: '2026-09-01',
      description: 'Date of shift attendance in YYYY-MM-DD format',
      aliases: ['attendance_date', 'date', 'punch_date', 'shift_date'],
    },
    {
      key: 'check_in_at',
      label: 'Check In Time',
      required: false,
      type: 'string',
      sampleValue: '08:55:00',
      description: 'Clock in time (HH:MM or HH:MM:SS) or full datetime',
      aliases: ['check_in_at', 'in_time', 'clock_in', 'check_in', 'punch_in', 'time_in'],
    },
    {
      key: 'check_out_at',
      label: 'Check Out Time',
      required: false,
      type: 'string',
      sampleValue: '17:05:00',
      description: 'Clock out time (HH:MM or HH:MM:SS) or full datetime',
      aliases: ['check_out_at', 'out_time', 'clock_out', 'check_out', 'punch_out', 'time_out'],
    },
    {
      key: 'shift_code',
      label: 'Shift Code / Name',
      required: false,
      type: 'string',
      sampleValue: 'MORNING',
      description: 'Shift code (e.g. MORNING, NIGHT, GENERAL). Defaults to employee default shift',
      aliases: ['shift_code', 'shift', 'shift_name', 'roster_shift'],
    },
    {
      key: 'status',
      label: 'Attendance Status',
      required: false,
      type: 'enum',
      options: ['present', 'absent', 'late', 'half_day', 'on_leave', 'holiday', 'weekly_off'],
      sampleValue: 'present',
      description: 'present, absent, late, half_day, on_leave, holiday, or weekly_off',
      aliases: ['status', 'attendance_status', 'state', 'att_status'],
    },
    {
      key: 'remarks',
      label: 'Remarks / Device ID',
      required: false,
      type: 'string',
      sampleValue: 'Biometric Machine Terminal #2',
      description: 'Source biometric terminal, device ID, or operator note',
      aliases: ['remarks', 'notes', 'comment', 'device_id', 'source_device'],
    },
  ],
};
