import type { ImportSchemaConfig } from '../../../components/import/types';

export const employeeImportSchema: ImportSchemaConfig = {
  entityTitle: 'Employees',
  templateFileName: 'erp_employees_import_template',
  uniqueIdentifierKey: 'employee_code',
  supportsUpsert: true,
  apiEndpoint: '/hr/employees/bulk-import',
  columns: [
    {
      key: 'employee_code',
      label: 'Employee Code',
      required: false,
      type: 'string',
      sampleValue: 'EMP-1001',
      description: 'Leave blank to auto-generate code',
      aliases: ['code', 'emp_id', 'staff_id', 'employee_id', 'id'],
    },
    {
      key: 'first_name',
      label: 'First Name',
      required: true,
      type: 'string',
      sampleValue: 'Rahim',
      aliases: ['fname', 'first name', 'given name', 'name'],
    },
    {
      key: 'last_name',
      label: 'Last Name',
      required: false,
      type: 'string',
      sampleValue: 'Uddin',
      aliases: ['lname', 'last name', 'surname'],
    },
    {
      key: 'phone',
      label: 'Phone Number',
      required: true,
      type: 'string',
      sampleValue: '+8801712345678',
      aliases: ['mobile', 'contact', 'phone number', 'cell'],
    },
    {
      key: 'email',
      label: 'Email Address',
      required: false,
      type: 'email',
      sampleValue: 'rahim.uddin@company.com',
      aliases: ['email', 'e-mail', 'mail'],
    },
    {
      key: 'department',
      label: 'Department',
      required: false,
      type: 'string',
      sampleValue: 'Cutting',
      description: 'Department name or department code',
      aliases: ['dept', 'department_name', 'department_code'],
    },
    {
      key: 'designation',
      label: 'Designation',
      required: false,
      type: 'string',
      sampleValue: 'Senior Tailor',
      description: 'Job title or designation name',
      aliases: ['role', 'designation_name', 'job_title', 'position'],
    },
    {
      key: 'employment_type',
      label: 'Employment Type',
      required: false,
      type: 'enum',
      options: ['permanent', 'contract', 'daily_wage', 'piece_rate', 'probation'],
      sampleValue: 'permanent',
      aliases: ['type', 'employment type', 'job type'],
    },
    {
      key: 'employment_status',
      label: 'Employment Status',
      required: false,
      type: 'enum',
      options: ['active', 'on_leave', 'suspended', 'resigned', 'terminated'],
      sampleValue: 'active',
      aliases: ['status', 'employment status'],
    },
    {
      key: 'date_of_joining',
      label: 'Date of Joining',
      required: false,
      type: 'date',
      sampleValue: '2025-01-15',
      description: 'YYYY-MM-DD',
      aliases: ['joining_date', 'join date', 'hire date', 'start date'],
    },
    {
      key: 'shift',
      label: 'Default Shift',
      required: false,
      type: 'string',
      sampleValue: 'Morning Shift',
      description: 'Shift name or code',
      aliases: ['shift_name', 'shift_code', 'work shift'],
    },
    {
      key: 'national_id',
      label: 'National ID / Passport',
      required: false,
      type: 'string',
      sampleValue: '19852691234567890',
      aliases: ['nid', 'national id', 'passport', 'nid_number'],
    },
    {
      key: 'bank_name',
      label: 'Bank Name',
      required: false,
      type: 'string',
      sampleValue: 'City Bank Ltd',
      aliases: ['bank'],
    },
    {
      key: 'bank_account_number',
      label: 'Bank Account Number',
      required: false,
      type: 'string',
      sampleValue: '11029384756',
      aliases: ['account_number', 'bank_account', 'account_no'],
    },
    {
      key: 'mobile_wallet_number',
      label: 'Mobile Wallet (bKash/Nagad)',
      required: false,
      type: 'string',
      sampleValue: '01712345678',
      aliases: ['bkash', 'nagad', 'mfs', 'wallet'],
    },
  ],
};
