import type { ImportSchemaConfig } from '../../../components/import/types';

export const salaryAdvanceImportSchema: ImportSchemaConfig = {
  entityTitle: 'Salary Advances & Loans',
  templateFileName: 'slicemart_salary_advances_import_template',
  uniqueIdentifierKey: 'advance_number',
  supportsUpsert: true,
  apiEndpoint: '/hr/payroll/advances/bulk-import',
  columns: [
    {
      key: 'employee_code',
      label: 'Employee Code',
      required: true,
      type: 'string',
      sampleValue: 'EMP-00101',
      description: 'Employee badge or employee code in staff directory',
      aliases: ['employee_code', 'emp_code', 'code', 'staff_id', 'employee_id'],
    },
    {
      key: 'advance_number',
      label: 'Advance Voucher Number',
      required: false,
      type: 'string',
      sampleValue: 'ADV-2026-0012',
      description: 'Unique loan/advance transaction number (auto-generated if omitted)',
      aliases: ['advance_number', 'advance_no', 'voucher_no', 'loan_no', 'ref_no'],
    },
    {
      key: 'amount',
      label: 'Principal Amount',
      required: true,
      type: 'number',
      sampleValue: '15000',
      description: 'Total disbursed salary advance amount',
      aliases: ['amount', 'advance_amount', 'loan_amount', 'total_amount', 'principal'],
    },
    {
      key: 'issued_on',
      label: 'Issue Date',
      required: false,
      type: 'date',
      sampleValue: '2026-09-01',
      description: 'Disbursement date in YYYY-MM-DD (defaults to today)',
      aliases: ['issued_on', 'date', 'issue_date', 'disbursed_on', 'disbursement_date'],
    },
    {
      key: 'installment_amount',
      label: 'Monthly Recovery Installment',
      required: false,
      type: 'number',
      sampleValue: '5000',
      description: 'Monthly payroll deduction amount (defaults to total amount)',
      aliases: ['installment_amount', 'monthly_deduction', 'installment', 'deduction_per_month'],
    },
    {
      key: 'recovered_amount',
      label: 'Already Recovered Amount',
      required: false,
      type: 'number',
      sampleValue: '0',
      description: 'Cumulative amount already recovered prior to migration (defaults to 0)',
      aliases: ['recovered_amount', 'already_recovered', 'paid_amount', 'cleared_amount'],
    },
    {
      key: 'recovery_start_period_code',
      label: 'Recovery Start Period Code',
      required: false,
      type: 'string',
      sampleValue: 'PAY-2026-09',
      description: 'Code of the payroll period when deductions begin',
      aliases: ['recovery_start_period_code', 'period_code', 'payroll_period', 'start_period'],
    },
    {
      key: 'status',
      label: 'Advance Status',
      required: false,
      type: 'enum',
      options: ['active', 'recovered', 'written_off'],
      sampleValue: 'active',
      description: 'active, recovered, or written_off (defaults to active)',
      aliases: ['status', 'advance_status', 'loan_status'],
    },
    {
      key: 'notes',
      label: 'Notes / Reason',
      required: false,
      type: 'string',
      sampleValue: 'Emergency medical loan advance',
      description: 'Context, sanction authority, or justification note',
      aliases: ['notes', 'remarks', 'reason', 'comment', 'description'],
    },
  ],
};
