import type { ImportSchemaConfig } from '../../../components/import/types';

export const shiftImportSchema: ImportSchemaConfig = {
  entityTitle: 'Work Shifts & Timings',
  templateFileName: 'slicemart_shifts_import_template',
  uniqueIdentifierKey: 'name',
  supportsUpsert: true,
  apiEndpoint: '/hr/shifts/bulk-import',
  columns: [
    {
      key: 'name',
      label: 'Shift Name',
      required: true,
      type: 'string',
      sampleValue: 'Morning Production Shift',
      description: 'Human readable name of work shift',
      aliases: ['name', 'shift_name', 'shift', 'title'],
    },
    {
      key: 'code',
      label: 'Shift Code',
      required: false,
      type: 'string',
      sampleValue: 'PROD-MORN',
      description: 'Unique shift code (auto-derived if blank)',
      aliases: ['code', 'shift_code', 'short_code'],
    },
    {
      key: 'start_time',
      label: 'Start Time',
      required: true,
      type: 'string',
      sampleValue: '08:00:00',
      description: 'Shift start time (e.g. 08:00 or 08:00:00)',
      aliases: ['start_time', 'start', 'in_time', 'begin_time', 'start_at'],
    },
    {
      key: 'end_time',
      label: 'End Time',
      required: true,
      type: 'string',
      sampleValue: '16:30:00',
      description: 'Shift conclusion time (e.g. 16:30 or 16:30:00)',
      aliases: ['end_time', 'end', 'out_time', 'finish_time', 'end_at'],
    },
    {
      key: 'break_minutes',
      label: 'Break Minutes',
      required: false,
      type: 'number',
      sampleValue: '45',
      description: 'Meal / tea break duration in minutes (defaults to 45)',
      aliases: ['break_minutes', 'break_duration', 'break_min', 'lunch_minutes'],
    },
    {
      key: 'grace_in_minutes',
      label: 'Grace In Minutes',
      required: false,
      type: 'number',
      sampleValue: '15',
      description: 'Leniency before attendance counts as late (defaults to 15)',
      aliases: ['grace_in_minutes', 'grace_minutes', 'grace_period', 'grace_in'],
    },
    {
      key: 'crosses_midnight',
      label: 'Crosses Midnight',
      required: false,
      type: 'boolean',
      sampleValue: 'false',
      description: 'True if shift spans across 12:00 AM into next day',
      aliases: ['crosses_midnight', 'is_night_shift', 'overnight', 'night_shift'],
    },
    {
      key: 'is_active',
      label: 'Is Active',
      required: false,
      type: 'boolean',
      sampleValue: 'true',
      description: 'True if active, false if retired',
      aliases: ['is_active', 'active', 'status'],
    },
  ],
};
