import type { ImportSchemaConfig } from '../../../components/import/types';

export const historicalInvoiceImportSchema: ImportSchemaConfig = {
  entityTitle: 'Historical Opening Invoices & AR Balances',
  templateFileName: 'erp_historical_invoices_import_template',
  uniqueIdentifierKey: 'invoice_number',
  supportsUpsert: true,
  apiEndpoint: '/sales/invoices/bulk-import',
  columns: [
    {
      key: 'invoice_number',
      label: 'Invoice Number',
      required: true,
      type: 'string',
      sampleValue: 'INV-2026-0089',
      description: 'Original legacy invoice or opening balance reference number',
      aliases: ['invoice_number', 'invoice_no', 'inv_no', 'bill_no', 'reference', 'doc_number'],
    },
    {
      key: 'customer_code',
      label: 'Customer Code / Name',
      required: true,
      type: 'string',
      sampleValue: 'CUST-001',
      description: 'Customer code or organization name. Auto-created if new',
      aliases: ['customer_code', 'party_code', 'customer', 'party', 'client_code', 'customer_name'],
    },
    {
      key: 'invoice_date',
      label: 'Invoice Date',
      required: true,
      type: 'date',
      sampleValue: '2026-08-01',
      description: 'Date invoice was originally issued (YYYY-MM-DD)',
      aliases: ['invoice_date', 'date', 'bill_date', 'doc_date', 'issue_date'],
    },
    {
      key: 'due_date',
      label: 'Payment Due Date',
      required: false,
      type: 'date',
      sampleValue: '2026-08-31',
      description: 'Date payment was or is due (defaults to invoice date)',
      aliases: ['due_date', 'payment_due', 'expiry_date', 'due'],
    },
    {
      key: 'total_amount',
      label: 'Total Invoice Amount',
      required: true,
      type: 'number',
      sampleValue: 45000.0,
      description: 'Gross invoice receivable amount',
      aliases: [
        'total_amount',
        'total',
        'invoice_amount',
        'invoice amount',
        'grand_total',
        'grand total',
        'gross_amount',
        'gross amount',
        'gross_total',
        'gross total',
        'amount',
      ],
    },
    {
      key: 'paid_amount',
      label: 'Amount Paid',
      required: false,
      type: 'number',
      sampleValue: 15000.0,
      description: 'Portion of invoice already cleared by customer (default: 0.0)',
      aliases: ['paid_amount', 'paid', 'amount_paid', 'received_amount', 'cleared'],
    },
    {
      key: 'status',
      label: 'Invoice Status',
      required: false,
      type: 'enum',
      options: ['draft', 'posted', 'partially_paid', 'paid', 'void'],
      sampleValue: 'partially_paid',
      description: 'draft, posted, partially_paid, paid, or void (auto-derived if blank)',
      aliases: ['status', 'payment_status', 'invoice_status'],
    },
    {
      key: 'notes',
      label: 'Notes / Memo',
      required: false,
      type: 'string',
      sampleValue: 'Opening balance migration from legacy Tally ERP',
      description: 'Internal audit or opening migration note',
      aliases: ['notes', 'description', 'remarks', 'memo'],
    },
  ],
};
