import type { ImportSchemaConfig } from '../../../components/import/types';

export const leadImportSchema: ImportSchemaConfig = {
  entityTitle: 'CRM Leads & Prospects',
  templateFileName: 'erp_crm_leads_import_template',
  uniqueIdentifierKey: 'lead_number',
  supportsUpsert: true,
  apiEndpoint: '/sales/leads/bulk-import',
  columns: [
    {
      key: 'lead_number',
      label: 'Lead Number',
      required: false,
      type: 'string',
      sampleValue: 'LD-260913-001',
      description: 'Unique lead reference number. Leave blank to auto-generate',
      aliases: ['lead_number', 'lead_no', 'lead_id', 'reference', 'code'],
    },
    {
      key: 'name',
      label: 'Contact / Lead Name',
      required: true,
      type: 'string',
      sampleValue: 'Tariqul Islam',
      description: 'Primary contact or decision maker name',
      aliases: ['name', 'lead_name', 'contact_name', 'full_name', 'customer_name', 'client_name'],
    },
    {
      key: 'company_name',
      label: 'Company Name',
      required: false,
      type: 'string',
      sampleValue: 'Apex Agro Industries',
      description: 'Organization or enterprise name if B2B',
      aliases: ['company_name', 'company', 'organization', 'business_name', 'account_name'],
    },
    {
      key: 'phone',
      label: 'Phone Number',
      required: false,
      type: 'string',
      sampleValue: '+8801712345678',
      description: 'Mobile or office contact telephone number',
      aliases: ['phone', 'mobile', 'contact_no', 'telephone', 'cell', 'phone_number'],
    },
    {
      key: 'email',
      label: 'Email Address',
      required: false,
      type: 'email',
      sampleValue: 'tariqul@apexagro.com',
      description: 'Business or personal contact email address',
      aliases: ['email', 'email_address', 'contact_email'],
    },
    {
      key: 'source',
      label: 'Lead Source',
      required: false,
      type: 'enum',
      options: ['walk_in', 'phone', 'referral', 'online', 'field_visit', 'other'],
      sampleValue: 'field_visit',
      description: 'Acquisition channel: walk_in, phone, referral, online, field_visit, or other',
      aliases: ['source', 'lead_source', 'channel', 'origin', 'acquisition_source'],
    },
    {
      key: 'stage',
      label: 'Pipeline Stage',
      required: false,
      type: 'enum',
      options: ['new', 'contacted', 'qualified', 'proposal', 'won', 'lost'],
      sampleValue: 'qualified',
      description: 'Stage: new, contacted, qualified, proposal, won, or lost',
      aliases: ['stage', 'pipeline_stage', 'status', 'lead_status'],
    },
    {
      key: 'assigned_to',
      label: 'Assigned Sales Rep',
      required: false,
      type: 'string',
      sampleValue: 'EMP-001',
      description: 'Sales representative employee code or user email',
      aliases: ['assigned_to', 'salesman', 'sales_rep', 'assigned_salesman', 'rep_email', 'salesman_code'],
    },
    {
      key: 'expected_value',
      label: 'Expected Value',
      required: false,
      type: 'number',
      sampleValue: 250000,
      description: 'Estimated opportunity contract value in currency',
      aliases: [
        'expected_value',
        'expected deal value',
        'expected_deal_value',
        'deal_value',
        'deal value',
        'deal_size',
        'deal size',
        'estimated_value',
        'amount',
        'value',
      ],
    },
    {
      key: 'expected_close_date',
      label: 'Expected Close Date',
      required: false,
      type: 'date',
      sampleValue: '2026-10-31',
      description: 'Anticipated deal conclusion date (YYYY-MM-DD)',
      aliases: ['expected_close_date', 'close_date', 'target_date', 'deadline'],
    },
    {
      key: 'notes',
      label: 'Requirements / Notes',
      required: false,
      type: 'string',
      sampleValue: 'Interested in bulk packaging solutions for Q4 rollout.',
      description: 'Commercial notes, customer pain points or special requests',
      aliases: ['notes', 'comments', 'remarks', 'description', 'requirements'],
    },
  ],
};
