import type { ImportSchemaConfig } from '../../../components/import/types';

export const priceListImportSchema: ImportSchemaConfig = {
  entityTitle: 'Customer Price Lists',
  templateFileName: 'erp_price_lists_import_template',
  uniqueIdentifierKey: 'product_sku',
  supportsUpsert: true,
  apiEndpoint: '/pricing/price-lists/bulk-import',
  columns: [
    {
      key: 'price_list_code',
      label: 'Price List Code',
      required: true,
      type: 'string',
      sampleValue: 'WHOLESALE',
      description: 'Code of price schedule (e.g. WHOLESALE, DISTRIBUTOR, VIP). Auto-created if new',
      aliases: ['price_list_code', 'price_list', 'list_code', 'tier', 'group', 'pricing_tier'],
    },
    {
      key: 'price_list_name',
      label: 'Price List Name',
      required: false,
      type: 'string',
      sampleValue: 'Wholesale B2B Schedule',
      description: 'Human-readable title for new price list',
      aliases: ['price_list_name', 'list_name', 'tier_name', 'name'],
    },
    {
      key: 'product_sku',
      label: 'Product SKU',
      required: true,
      type: 'string',
      sampleValue: 'SKU-500ML-JAR',
      description: 'Existing catalog product SKU identifier',
      aliases: ['product_sku', 'sku', 'item_code', 'code', 'product_code', 'barcode'],
    },
    {
      key: 'unit_price',
      label: 'Special Unit Price',
      required: true,
      type: 'number',
      sampleValue: 185.5,
      description: 'Scheduled unit price for this item on the price list',
      aliases: ['unit_price', 'price', 'special_price', 'rate', 'selling_price', 'tier_price'],
    },
    {
      key: 'min_quantity',
      label: 'Minimum Quantity',
      required: false,
      type: 'number',
      sampleValue: 50,
      description: 'Quantity break lower bound (default: 1.0)',
      aliases: [
        'min_quantity',
        'min_qty',
        'min qty',
        'min qty break',
        'min_qty_break',
        'quantity_break',
        'quantity break',
        'tier_qty',
        'break_qty',
        'moq',
      ],
    },
    {
      key: 'discount_percentage',
      label: 'Discount Percentage (%)',
      required: false,
      type: 'number',
      sampleValue: 5.0,
      description: 'Optional discount percentage applied at this tier',
      aliases: ['discount_percentage', 'discount_pct', 'discount', 'discount_%', 'rebate'],
    },
  ],
};
