import type { ImportSchemaConfig } from '../../../components/import/types';

export const salesTargetImportSchema: ImportSchemaConfig = {
  entityTitle: 'Salesman Targets & Quotas',
  templateFileName: 'erp_salesman_targets_import_template',
  uniqueIdentifierKey: 'employee_code',
  supportsUpsert: true,
  apiEndpoint: '/sales/targets/bulk-import',
  columns: [
    {
      key: 'employee_code',
      label: 'Employee / Salesman Code',
      required: true,
      type: 'string',
      sampleValue: 'EMP-001',
      description: 'Employee code of the designated sales executive or agent',
      aliases: ['employee_code', 'salesman_code', 'rep_code', 'salesman', 'employee', 'agent_code', 'sales_rep'],
    },
    {
      key: 'period_month',
      label: 'Target Month (YYYY-MM)',
      required: true,
      type: 'string',
      sampleValue: '2026-09',
      description: 'Target month formatted as YYYY-MM (e.g. 2026-09)',
      aliases: ['period_month', 'month', 'period', 'target_month', 'year_month'],
    },
    {
      key: 'target_name',
      label: 'Target Campaign Title',
      required: false,
      type: 'string',
      sampleValue: 'Q3 Wholesale Growth Campaign',
      description: 'Optional campaign or target objective name',
      aliases: ['target_name', 'target_title', 'campaign', 'title', 'name'],
    },
    {
      key: 'target_amount',
      label: 'Target Revenue Quota',
      required: true,
      type: 'number',
      sampleValue: 500000.0,
      description: 'Assigned gross revenue target in currency',
      aliases: [
        'target_amount',
        'target',
        'quota',
        'quota amount',
        'target quota amount',
        'target_quota_amount',
        'revenue_target',
        'revenue quota',
        'sales_target',
        'amount',
      ],
    },
    {
      key: 'achieved_amount',
      label: 'Achieved Revenue',
      required: false,
      type: 'number',
      sampleValue: 125000.0,
      description: 'Current or opening achieved sales revenue (default: 0.0)',
      aliases: ['achieved_amount', 'achieved', 'actual_sales', 'current_achieved', 'sales_done'],
    },
    {
      key: 'status',
      label: 'Target Status',
      required: false,
      type: 'enum',
      options: ['active', 'completed', 'cancelled'],
      sampleValue: 'active',
      description: 'active, completed, or cancelled (default: active)',
      aliases: ['status', 'target_status'],
    },
    {
      key: 'notes',
      label: 'Strategy & KPI Notes',
      required: false,
      type: 'string',
      sampleValue: 'Focus on expanding into the North division wholesale accounts',
      description: 'Sales leadership directives or territory remarks',
      aliases: ['notes', 'comments', 'remarks', 'strategy'],
    },
  ],
};
