import type { ImportSchemaConfig } from '../../../components/import/types';

export const bomImportSchema: ImportSchemaConfig = {
  entityTitle: 'Bills of Materials (Recipes)',
  templateFileName: 'erp_bom_import_template',
  uniqueIdentifierKey: 'finished_sku',
  supportsUpsert: true,
  apiEndpoint: '/bill-of-materials/bulk-import',
  columns: [
    {
      key: 'finished_sku',
      label: 'Finished Product SKU',
      required: true,
      type: 'string',
      sampleValue: 'TSHIRT-BLK-M',
      description: 'SKU of the final product to be manufactured',
      aliases: ['finished_sku', 'parent_sku', 'output_sku', 'product_sku', 'fg_code'],
    },
    {
      key: 'bom_name',
      label: 'Recipe / BOM Name',
      required: false,
      type: 'string',
      sampleValue: 'Standard Men T-Shirt Recipe',
      description: 'Human-readable name of the recipe or assembly bill',
      aliases: ['bom_name', 'recipe_name', 'bom_recipe_name', 'recipe', 'name', 'title'],
    },
    {
      key: 'version',
      label: 'BOM Version',
      required: false,
      type: 'string',
      sampleValue: 'v1.0',
      description: 'Engineering version (e.g. v1.0, v2.1, 2026-R1)',
      aliases: ['version', 'bom_version', 'revision', 'rev'],
    },
    {
      key: 'output_quantity',
      label: 'Output Yield Quantity',
      required: false,
      type: 'number',
      sampleValue: 1,
      description: 'Number of finished units produced by this recipe batch',
      aliases: ['output_quantity', 'batch_size', 'yield', 'output_qty'],
    },
    {
      key: 'output_unit',
      label: 'Output Unit',
      required: false,
      type: 'string',
      sampleValue: 'PCS',
      description: 'Unit of finished goods (defaults to product base unit)',
      aliases: ['output_unit', 'yield_unit', 'unit'],
    },
    {
      key: 'component_sku',
      label: 'Raw Material SKU',
      required: true,
      type: 'string',
      sampleValue: 'FABRIC-COTTON-BLK',
      description: 'SKU of the raw material, packaging, or ingredient component',
      aliases: ['component_sku', 'raw_material_sku', 'material_code', 'item_code', 'ingredient'],
    },
    {
      key: 'component_quantity',
      label: 'Required Quantity',
      required: true,
      type: 'number',
      sampleValue: 1.25,
      description: 'Gross quantity of material required per batch',
      aliases: ['component_quantity', 'quantity', 'qty', 'required_qty'],
    },
    {
      key: 'component_unit',
      label: 'Component Unit',
      required: false,
      type: 'string',
      sampleValue: 'MTR',
      description: 'Measurement unit of material (e.g. KG, MTR, LTR, PCS)',
      aliases: ['component_unit', 'material_unit', 'uom'],
    },
    {
      key: 'scrap_percentage',
      label: 'Scrap / Wastage %',
      required: false,
      type: 'number',
      sampleValue: 3.5,
      description: 'Expected cutting or manufacturing scrap percentage',
      aliases: ['scrap_percentage', 'wastage', 'scrap', 'waste_percentage', 'loss'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      options: ['draft', 'active', 'archived'],
      sampleValue: 'active',
      description: 'draft, active, or archived',
      aliases: ['status', 'state'],
    },
  ],
};
