import type { ImportSchemaConfig } from '../../../components/import/types';

export const partyImportSchema: ImportSchemaConfig = {
  entityTitle: 'Parties (Customers & Suppliers)',
  templateFileName: 'slicemart_parties_import_template',
  uniqueIdentifierKey: 'code',
  supportsUpsert: true,
  apiEndpoint: '/parties/bulk-import',
  columns: [
    {
      key: 'code',
      label: 'Party Code',
      required: false,
      type: 'string',
      sampleValue: 'CUST-1001',
      description: 'Leave blank to auto-generate code (CUST-XXXX or SUP-XXXX)',
      aliases: ['party_code', 'customer_code', 'supplier_code', 'id', 'account_id'],
    },
    {
      key: 'name',
      label: 'Party / Company Name',
      required: true,
      type: 'string',
      sampleValue: 'Rahim Textiles & Garments Ltd',
      aliases: ['company_name', 'party_name', 'customer_name', 'supplier_name', 'title'],
    },
    {
      key: 'legal_name',
      label: 'Legal / Registered Name',
      required: false,
      type: 'string',
      sampleValue: 'Rahim Textiles & Garments Private Limited',
      aliases: ['registered_name', 'legal_entity'],
    },
    {
      key: 'role',
      label: 'Party Role',
      required: false,
      type: 'string',
      sampleValue: 'customer',
      description: 'customer, supplier, dealer, agent, or both',
      aliases: ['party_role', 'type_of_party', 'relation', 'roles'],
    },
    {
      key: 'type',
      label: 'Entity Type',
      required: false,
      type: 'enum',
      options: ['business', 'individual'],
      sampleValue: 'business',
      description: 'business or individual',
      aliases: ['business_type', 'entity_type'],
    },
    {
      key: 'phone',
      label: 'Phone Number',
      required: false,
      type: 'string',
      sampleValue: '+8801711223344',
      aliases: ['mobile', 'contact_number', 'telephone', 'cell'],
    },
    {
      key: 'email',
      label: 'Email Address',
      required: false,
      type: 'email',
      sampleValue: 'procurement@rahimtextiles.com',
      aliases: ['email_address', 'mail'],
    },
    {
      key: 'tax_identifier',
      label: 'BIN / Tax ID',
      required: false,
      type: 'string',
      sampleValue: 'BIN-123456789',
      description: 'Business Identification Number (BIN) or TIN',
      aliases: ['bin', 'tin', 'vat_number', 'tax_id'],
    },
    {
      key: 'credit_limit',
      label: 'Credit Limit',
      required: false,
      type: 'number',
      sampleValue: 500000.0,
      description: 'Maximum credit allowed',
      aliases: ['limit', 'max_credit'],
    },
    {
      key: 'credit_days',
      label: 'Credit Days',
      required: false,
      type: 'number',
      sampleValue: 30,
      description: 'Payment terms in days',
      aliases: ['terms', 'payment_terms', 'days'],
    },
    {
      key: 'opening_balance',
      label: 'Opening Balance',
      required: false,
      type: 'number',
      sampleValue: 0.0,
      description: 'Initial ledger balance (+ for receivable, - for payable)',
      aliases: ['initial_balance', 'balance'],
    },
    {
      key: 'address',
      label: 'Street Address',
      required: false,
      type: 'string',
      sampleValue: 'House 12, Road 4, Sector 3, Uttara',
      aliases: ['address_line1', 'street', 'location'],
    },
    {
      key: 'city',
      label: 'City',
      required: false,
      type: 'string',
      sampleValue: 'Dhaka',
      aliases: ['town', 'district'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      options: ['active', 'inactive', 'blacklisted'],
      sampleValue: 'active',
      aliases: ['party_status', 'state'],
    },
  ],
  sampleRows: [
    {
      code: 'CUST-1001',
      name: 'Rahim Textiles & Garments Ltd',
      legal_name: 'Rahim Textiles & Garments Private Limited',
      role: 'customer',
      type: 'business',
      phone: '+8801711223344',
      email: 'procurement@rahimtextiles.com',
      tax_identifier: 'BIN-123456789',
      credit_limit: 500000,
      credit_days: 30,
      opening_balance: 0,
      address: 'House 12, Road 4, Sector 3, Uttara',
      city: 'Dhaka',
      status: 'active',
    },
    {
      code: 'SUP-2001',
      name: 'Bengal Thread & Accessories Mills',
      legal_name: 'Bengal Thread & Accessories Mills LLC',
      role: 'supplier',
      type: 'business',
      phone: '+8801811556677',
      email: 'orders@bengalthread.com',
      tax_identifier: 'BIN-987654321',
      credit_limit: 200000,
      credit_days: 15,
      opening_balance: 0,
      address: 'Plot 88, BSCIC Industrial Area',
      city: 'Narayanganj',
      status: 'active',
    },
    {
      code: 'DEAL-3001',
      name: 'Chattogram Fashion Hub',
      legal_name: 'Chattogram Fashion Hub Ltd',
      role: 'dealer',
      type: 'business',
      phone: '+8801911889900',
      email: 'info@ctgfashionhub.com',
      tax_identifier: 'BIN-456789123',
      credit_limit: 1000000,
      credit_days: 45,
      opening_balance: 50000,
      address: 'Station Road, GEC Circle',
      city: 'Chattogram',
      status: 'active',
    },
  ],
};
