import type { ImportSchemaConfig } from '../../../components/import/types';

export const productImportSchema: ImportSchemaConfig = {
  entityTitle: 'Products',
  templateFileName: 'erp_products_import_template',
  uniqueIdentifierKey: 'sku',
  supportsUpsert: true,
  apiEndpoint: '/products/bulk-import',
  columns: [
    {
      key: 'sku',
      label: 'SKU / Item Code',
      required: false,
      type: 'string',
      sampleValue: 'TSHIRT-BLK-M',
      description: 'Leave blank to auto-generate unique SKU',
      aliases: ['item_code', 'item code', 'product_code', 'code', 'product_id'],
    },
    {
      key: 'name',
      label: 'Product Name',
      required: true,
      type: 'string',
      sampleValue: 'Premium Black Cotton T-Shirt (M)',
      aliases: ['item_name', 'item name', 'product_name', 'title', 'item'],
    },
    {
      key: 'type',
      label: 'Product Type',
      required: false,
      type: 'enum',
      options: ['finished', 'semi_finished', 'raw_material', 'packaging', 'consumable', 'service'],
      sampleValue: 'finished',
      description: 'finished, semi_finished, raw_material, etc.',
      aliases: ['product_type', 'item_type', 'classification'],
    },
    {
      key: 'category',
      label: 'Category',
      required: false,
      type: 'string',
      sampleValue: 'Apparel',
      description: 'Category name or code (auto-created if not exists)',
      aliases: ['category_name', 'cat', 'group'],
    },
    {
      key: 'brand',
      label: 'Brand',
      required: false,
      type: 'string',
      sampleValue: 'SliceFit',
      description: 'Brand name (auto-created if not exists)',
      aliases: ['brand_name', 'make', 'manufacturer'],
    },
    {
      key: 'unit',
      label: 'Measurement Unit',
      required: false,
      type: 'string',
      sampleValue: 'PCS',
      description: 'Unit code (e.g. PCS, KG, MTR, PACK, BOX)',
      aliases: ['uom', 'base_unit', 'unit_code', 'units'],
    },
    {
      key: 'cost_price',
      label: 'Cost Price',
      required: false,
      type: 'number',
      sampleValue: 280.0,
      description: 'Purchase or manufacturing cost per unit',
      aliases: ['standard_cost', 'cost', 'unit_cost', 'purchase_price', 'buying_price'],
    },
    {
      key: 'selling_price',
      label: 'Selling Price',
      required: false,
      type: 'number',
      sampleValue: 550.0,
      description: 'Default retail / sales price per unit',
      aliases: ['default_sale_price', 'sale_price', 'mrp', 'rate', 'price'],
    },
    {
      key: 'barcode',
      label: 'Barcode / EAN',
      required: false,
      type: 'string',
      sampleValue: '8901234567890',
      description: 'UPC, EAN-13, or internal barcode',
      aliases: ['ean', 'upc', 'barcode_number'],
    },
    {
      key: 'opening_stock',
      label: 'Opening Stock',
      required: false,
      type: 'number',
      sampleValue: 100,
      description: 'Initial stock on hand at default warehouse',
      aliases: ['initial_stock', 'stock', 'qty', 'quantity', 'stock_qty'],
    },
    {
      key: 'reorder_level',
      label: 'Reorder Level',
      required: false,
      type: 'number',
      sampleValue: 20,
      description: 'Threshold alert for low stock',
      aliases: ['min_stock', 'reorder_point', 'minimum_stock'],
    },
    {
      key: 'status',
      label: 'Status',
      required: false,
      type: 'enum',
      options: ['active', 'draft', 'discontinued', 'archived'],
      sampleValue: 'active',
      aliases: ['item_status', 'state'],
    },
    {
      key: 'description',
      label: 'Description',
      required: false,
      type: 'string',
      sampleValue: '100% combed cotton 180 GSM bio-washed fabric.',
      aliases: ['desc', 'details', 'notes'],
    },
  ],
  sampleRows: [
    {
      sku: 'TSHIRT-BLK-M',
      name: 'Premium Black Cotton T-Shirt (M)',
      type: 'finished',
      category: 'Apparel',
      brand: 'SliceFit',
      unit: 'PCS',
      cost_price: 280,
      selling_price: 550,
      barcode: '8901234567890',
      opening_stock: 120,
      reorder_level: 25,
      status: 'active',
      description: '100% combed cotton 180 GSM bio-washed fabric.',
    },
    {
      sku: 'JEANS-SLM-32',
      name: 'Slim Fit Indigo Denim Jeans (32)',
      type: 'finished',
      category: 'Denim',
      brand: 'SliceFit',
      unit: 'PCS',
      cost_price: 650,
      selling_price: 1350,
      barcode: '8901234567891',
      opening_stock: 75,
      reorder_level: 15,
      status: 'active',
      description: '98% cotton 2% elastane stretch denim.',
    },
    {
      sku: 'YARN-CTN-30S',
      name: '30s Combed Cotton Yarn Cone',
      type: 'raw_material',
      category: 'Yarns',
      brand: 'Square Textiles',
      unit: 'KG',
      cost_price: 420,
      selling_price: 480,
      barcode: '',
      opening_stock: 500,
      reorder_level: 100,
      status: 'active',
      description: 'High tensile strength ring spun yarn for knitting.',
    },
  ],
};
