import type { ImportSchemaConfig } from '../../../components/import/types';

export const unitImportSchema: ImportSchemaConfig = {
  entityTitle: 'Units of Measure',
  templateFileName: 'erp_units_import_template',
  uniqueIdentifierKey: 'code',
  supportsUpsert: true,
  apiEndpoint: '/units/bulk-import',
  columns: [
    {
      key: 'code',
      label: 'Unit Code',
      required: true,
      type: 'string',
      sampleValue: 'KG',
      description: 'Standard unit abbreviation or code (e.g. KG, PCS, LTR, MTR, BOX)',
      aliases: ['unit_code', 'uom', 'unit', 'code', 'symbol'],
    },
    {
      key: 'name',
      label: 'Unit Name',
      required: true,
      type: 'string',
      sampleValue: 'Kilogram',
      description: 'Full name of the measurement unit',
      aliases: ['unit_name', 'name', 'title'],
    },
    {
      key: 'type',
      label: 'Unit Type',
      required: false,
      type: 'enum',
      options: ['weight', 'volume', 'length', 'piece', 'time'],
      sampleValue: 'weight',
      description: 'weight, volume, length, piece, or time (defaults to piece)',
      aliases: ['unit_type', 'type', 'dimension', 'family'],
    },
    {
      key: 'precision',
      label: 'Decimal Precision',
      required: false,
      type: 'number',
      sampleValue: 3,
      description: 'Number of decimal places (0 to 9)',
      aliases: ['precision', 'decimals', 'decimal_places', 'scale'],
    },
    {
      key: 'is_base',
      label: 'Is Base Unit',
      required: false,
      type: 'boolean',
      sampleValue: true,
      description: 'TRUE if this is the fundamental unit of measure in its family',
      aliases: ['is_base', 'base', 'base_unit'],
    },
    {
      key: 'is_active',
      label: 'Active Status',
      required: false,
      type: 'boolean',
      sampleValue: true,
      description: 'TRUE or FALSE (defaults to TRUE)',
      aliases: ['status', 'active', 'is_active', 'enabled'],
    },
  ],
};
