import type { ImportSchemaConfig } from '../../../components/import/types';

export const warehouseImportSchema: ImportSchemaConfig = {
  entityTitle: 'Warehouses & Bins',
  templateFileName: 'erp_warehouses_import_template',
  uniqueIdentifierKey: 'code',
  supportsUpsert: true,
  apiEndpoint: '/warehouses/bulk-import',
  columns: [
    {
      key: 'code',
      label: 'Warehouse Code',
      required: false,
      type: 'string',
      sampleValue: 'WH-CENTRAL',
      description: 'Unique warehouse code. Leave blank to auto-generate',
      aliases: ['warehouse_code', 'code', 'slug', 'id'],
    },
    {
      key: 'name',
      label: 'Warehouse Name',
      required: true,
      type: 'string',
      sampleValue: 'Central Distribution Hub',
      description: 'Full name of the warehouse or depot',
      aliases: ['warehouse_name', 'warehouse', 'name', 'depot', 'store'],
    },
    {
      key: 'type',
      label: 'Facility Type',
      required: false,
      type: 'enum',
      options: ['general', 'raw_materials', 'finished_goods', 'transit', 'quarantine', 'scrap'],
      sampleValue: 'general',
      description: 'general, raw_materials, finished_goods, transit, quarantine, or scrap',
      aliases: ['warehouse_type', 'type', 'category'],
    },
    {
      key: 'address',
      label: 'Physical Address',
      required: false,
      type: 'string',
      sampleValue: 'Plot 14, Sector 7, Uttara, Dhaka',
      description: 'Physical location or street address',
      aliases: ['location_address', 'address', 'location', 'street'],
    },
    {
      key: 'locations',
      label: 'Initial Bins & Racks',
      required: false,
      type: 'string',
      sampleValue: 'Rack-A1, Rack-A2, Bin-01, Bin-02',
      description: 'Comma-separated location/bin codes to auto-create inside this warehouse',
      aliases: ['bins', 'locations', 'storage_bins', 'racks', 'zones'],
    },
    {
      key: 'allows_negative_stock',
      label: 'Allow Negative Stock',
      required: false,
      type: 'boolean',
      sampleValue: false,
      description: 'TRUE or FALSE (defaults to FALSE for strict inventory control)',
      aliases: ['negative_stock', 'allow_negative', 'allows_negative_stock'],
    },
    {
      key: 'is_default',
      label: 'Default Warehouse',
      required: false,
      type: 'boolean',
      sampleValue: false,
      description: 'TRUE if this is the default fulfillment warehouse',
      aliases: ['default', 'is_default', 'primary'],
    },
    {
      key: 'is_active',
      label: 'Active Status',
      required: false,
      type: 'boolean',
      sampleValue: true,
      description: 'TRUE or FALSE (defaults to TRUE)',
      aliases: ['status', 'active', 'is_active', 'enabled'],
    },
  ],
};
