import type { ImportSchemaConfig } from '../../../components/import/types';

export const openingStockImportSchema: ImportSchemaConfig = {
  entityTitle: 'Initial Stock Balances & Batches',
  templateFileName: 'slicemart_opening_stock_import_template',
  uniqueIdentifierKey: 'sku',
  supportsUpsert: true,
  apiEndpoint: '/inventory/opening-stock/bulk-import',
  columns: [
    {
      key: 'sku',
      label: 'Product SKU',
      required: true,
      type: 'string',
      sampleValue: 'SKU-DRY-RICE-001',
      description: 'Existing item SKU code in product catalogue',
      aliases: ['product_sku', 'sku', 'item_code', 'product_code', 'code', 'barcode'],
    },
    {
      key: 'warehouse_code',
      label: 'Warehouse Code / Name',
      required: true,
      type: 'string',
      sampleValue: 'WH-CENTRAL',
      description: 'Warehouse code (e.g. WH-CENTRAL) or facility name',
      aliases: ['warehouse', 'warehouse_code', 'warehouse_name', 'facility', 'depot', 'store'],
    },
    {
      key: 'quantity',
      label: 'Opening Quantity',
      required: true,
      type: 'number',
      sampleValue: 250,
      description: 'Physical on-hand count (must be positive number)',
      aliases: ['qty', 'quantity', 'count', 'opening_stock', 'stock', 'on_hand', 'units'],
    },
    {
      key: 'unit_cost',
      label: 'Unit Cost Valuation',
      required: false,
      type: 'number',
      sampleValue: 45.0,
      description: 'Weighted average purchase unit cost',
      aliases: ['cost', 'unit_cost', 'cost_price', 'average_cost', 'rate', 'valuation_rate'],
    },
    {
      key: 'location_code',
      label: 'Bin / Rack Location',
      required: false,
      type: 'string',
      sampleValue: 'Rack-A1',
      description: 'Internal storage bin or shelf code (auto-created if new)',
      aliases: ['bin', 'location', 'location_code', 'rack', 'shelf', 'bin_code'],
    },
    {
      key: 'batch_code',
      label: 'Batch / Lot Number',
      required: false,
      type: 'string',
      sampleValue: 'LOT-2026-09-001',
      description: 'Manufacturer or production lot number for FIFO/FEFO tracking',
      aliases: ['batch', 'batch_code', 'batch_number', 'lot', 'lot_number', 'lot_code'],
    },
    {
      key: 'expiry_date',
      label: 'Batch Expiry Date',
      required: false,
      type: 'date',
      sampleValue: '2027-12-31',
      description: 'Expiration date in YYYY-MM-DD format',
      aliases: ['expiry', 'expiry_date', 'exp_date', 'expiration', 'best_before'],
    },
    {
      key: 'stock_state',
      label: 'Stock State',
      required: false,
      type: 'enum',
      options: ['available', 'reserved', 'quarantine', 'damaged'],
      sampleValue: 'available',
      description: 'available, reserved, quarantine, or damaged (defaults to available)',
      aliases: ['state', 'stock_state', 'status', 'inventory_status'],
    },
  ],
};
