import type { ImportSchemaConfig } from '../../../components/import/types';

export const bankStatementImportSchema: ImportSchemaConfig = {
  entityTitle: 'Bank Statement Feeds',
  templateFileName: 'slicemart_bank_statement_import_template',
  uniqueIdentifierKey: 'reference_number',
  supportsUpsert: true,
  apiEndpoint: '/finance/bank-transactions/bulk-import',
  columns: [
    {
      key: 'bank_account',
      label: 'Bank Account / Number',
      type: 'string',
      required: false,
      description: 'Account number or bank account name in ERP. Defaults to primary bank if omitted.',
      aliases: ['account_number', 'bank_name', 'account_name', 'bank', 'bank_acc'],
    },
    {
      key: 'transaction_date',
      label: 'Transaction Date',
      type: 'date',
      required: true,
      description: 'Date value appeared on bank statement (YYYY-MM-DD).',
      aliases: ['date', 'value_date', 'booking_date', 'txn_date'],
    },
    {
      key: 'reference_number',
      label: 'Reference / Cheque #',
      type: 'string',
      required: false,
      description: 'Cheque number, UTR, EFT tracking number, or bank transaction ID.',
      aliases: ['reference', 'cheque_no', 'chq_no', 'utr', 'txn_id', 'ref_no'],
    },
    {
      key: 'description',
      label: 'Description / Particulars',
      type: 'string',
      required: true,
      description: 'Narration, payee/payer details, or bank statement transaction particulars.',
      aliases: ['particulars', 'narration', 'memo', 'details', 'transaction_details'],
    },
    {
      key: 'withdrawal',
      label: 'Withdrawal / Debit (-)',
      type: 'number',
      required: false,
      description: 'Money leaving bank account (payments, fees, debits).',
      aliases: ['debit', 'dr', 'paid_out', 'outflow', 'withdraw'],
    },
    {
      key: 'deposit',
      label: 'Deposit / Credit (+)',
      type: 'number',
      required: false,
      description: 'Money entering bank account (receipts, transfers, credits).',
      aliases: ['credit', 'cr', 'paid_in', 'inflow', 'received'],
    },
    {
      key: 'balance_after',
      label: 'Closing Balance',
      type: 'number',
      required: false,
      description: 'Running bank statement balance after the transaction.',
      aliases: ['balance', 'running_balance', 'closing_balance', 'statement_balance'],
    },
  ],
  sampleRows: [
    {
      bank_account: 'OP-DEFAULT-01',
      transaction_date: '2026-02-01',
      reference_number: 'CHQ-882910',
      description: 'Vendor payment clearing - Apex Packaging',
      withdrawal: 125000,
      deposit: 0,
      balance_after: 875000,
    },
    {
      bank_account: 'OP-DEFAULT-01',
      transaction_date: '2026-02-03',
      reference_number: 'EFT-992011',
      description: 'Customer RTGS remittance - Bengal Retail',
      withdrawal: 0,
      deposit: 340000,
      balance_after: 1215000,
    },
    {
      bank_account: 'OP-DEFAULT-01',
      transaction_date: '2026-02-05',
      reference_number: 'CHG-FEB26',
      description: 'Monthly ledger servicing charge',
      withdrawal: 1500,
      deposit: 0,
      balance_after: 1213500,
    },
  ],
};
