import type { ImportSchemaConfig } from '../../../components/import/types';

export const chartOfAccountsImportSchema: ImportSchemaConfig = {
  entityTitle: 'Chart of Accounts',
  templateFileName: 'erp_chart_of_accounts_import_template',
  uniqueIdentifierKey: 'account_code',
  supportsUpsert: true,
  apiEndpoint: '/finance/accounts/bulk-import',
  columns: [
    {
      key: 'account_code',
      label: 'Account Code',
      type: 'string',
      required: true,
      sampleValue: '1010',
      description: 'Unique GL account number or code (e.g. 1010, 2010).',
      aliases: ['code', 'account_number', 'gl_code', 'acc_code', 'ac_code', 'account_no'],
    },
    {
      key: 'name',
      label: 'Account Name',
      type: 'string',
      required: true,
      sampleValue: 'Petty Cash - Factory Floor',
      description: 'Official title of the ledger account.',
      aliases: ['account_name', 'title', 'ledger_name', 'account_title', 'description'],
    },
    {
      key: 'account_type',
      label: 'Account Type',
      type: 'enum',
      required: true,
      options: ['asset', 'liability', 'equity', 'income', 'expense', 'revenue'],
      sampleValue: 'asset',
      description: 'Financial statement classification: asset, liability, equity, income, or expense.',
      aliases: ['type', 'category', 'statement_class', 'classification'],
    },
    {
      key: 'account_subtype',
      label: 'Subtype / Group Name',
      type: 'string',
      required: false,
      sampleValue: 'Cash and Cash Equivalents',
      description: 'Sub-classification (e.g. Current Assets, Operating Revenue, Cost of Goods Sold).',
      aliases: ['subtype', 'sub_type', 'group', 'sub_group', 'header'],
    },
    {
      key: 'parent_code',
      label: 'Parent Account Code',
      type: 'string',
      required: false,
      sampleValue: '1000',
      description: 'Account code of the parent group account for tree hierarchy.',
      aliases: ['parent_account_code', 'parent', 'parent_acc', 'parent_id'],
    },
    {
      key: 'is_group',
      label: 'Is Header Group',
      type: 'boolean',
      required: false,
      sampleValue: false,
      description: 'True if this is a header category group that contains sub-accounts.',
      aliases: ['group', 'is_header', 'is_summary', 'has_children'],
    },
    {
      key: 'normal_balance',
      label: 'Normal Balance',
      type: 'enum',
      required: false,
      options: ['debit', 'credit'],
      sampleValue: 'debit',
      description: 'Accounting normal balance: debit (Assets/Expenses) or credit (Liabilities/Equity/Income).',
      aliases: ['balance_type', 'dr_cr', 'normal_dr_cr', 'nature'],
    },
    {
      key: 'is_active',
      label: 'Active Status',
      type: 'boolean',
      required: false,
      sampleValue: true,
      description: 'Whether account is currently active for journal entries.',
      aliases: ['active', 'status', 'enabled'],
    },
  ],
  sampleRows: [
    {
      account_code: '1010',
      name: 'Petty Cash - Factory Floor',
      account_type: 'asset',
      account_subtype: 'Cash and Cash Equivalents',
      parent_code: '1000',
      is_group: false,
      normal_balance: 'debit',
      is_active: true,
    },
    {
      account_code: '1020',
      name: 'Dutch Bangla Bank - Operating A/C',
      account_type: 'asset',
      account_subtype: 'Bank Accounts',
      parent_code: '1000',
      is_group: false,
      normal_balance: 'debit',
      is_active: true,
    },
    {
      account_code: '2010',
      name: 'Trade Accounts Payable',
      account_type: 'liability',
      account_subtype: 'Current Liabilities',
      parent_code: '2000',
      is_group: false,
      normal_balance: 'credit',
      is_active: true,
    },
    {
      account_code: '3010',
      name: 'Retained Earnings',
      account_type: 'equity',
      account_subtype: 'Shareholders Equity',
      parent_code: '3000',
      is_group: false,
      normal_balance: 'credit',
      is_active: true,
    },
    {
      account_code: '4010',
      name: 'Fabric & Garments Wholesale Sales',
      account_type: 'income',
      account_subtype: 'Operating Revenue',
      parent_code: '4000',
      is_group: false,
      normal_balance: 'credit',
      is_active: true,
    },
    {
      account_code: '5010',
      name: 'Direct Raw Material Cost',
      account_type: 'expense',
      account_subtype: 'Cost of Goods Sold',
      parent_code: '5000',
      is_group: false,
      normal_balance: 'debit',
      is_active: true,
    },
  ],
};
