import type { ImportSchemaConfig } from '../../../components/import/types';

export const fixedAssetImportSchema: ImportSchemaConfig = {
  entityTitle: 'Fixed Assets Register',
  templateFileName: 'slicemart_fixed_assets_import_template',
  uniqueIdentifierKey: 'asset_code',
  supportsUpsert: true,
  apiEndpoint: '/assets/bulk-import',
  columns: [
    {
      key: 'asset_code',
      label: 'Asset Code / Tag #',
      type: 'string',
      required: false,
      description: 'Unique asset tracking code or barcode tag (auto-generated if omitted).',
      aliases: ['code', 'asset_tag', 'tag_number', 'asset_id', 'barcode'],
    },
    {
      key: 'name',
      label: 'Asset Description / Name',
      type: 'string',
      required: true,
      description: 'Descriptive title of the capital fixed asset.',
      aliases: ['asset_name', 'title', 'description', 'equipment_name'],
    },
    {
      key: 'category',
      label: 'Asset Category',
      type: 'string',
      required: true,
      description: 'Category name or classification (e.g. Machinery, Vehicles, IT Hardware). Auto-created if new.',
      aliases: ['asset_category', 'category_name', 'class', 'asset_class', 'group'],
    },
    {
      key: 'purchase_date',
      label: 'Purchase Date',
      type: 'date',
      required: false,
      description: 'Acquisition or capitalization date (YYYY-MM-DD). Defaults to today if omitted.',
      aliases: ['acquisition_date', 'date_purchased', 'bought_date', 'capitalization_date'],
    },
    {
      key: 'purchase_cost',
      label: 'Purchase Cost',
      type: 'number',
      required: true,
      description: 'Historical acquisition purchase cost in BDT/base currency.',
      aliases: ['cost', 'acquisition_cost', 'price', 'original_cost', 'purchase_price'],
    },
    {
      key: 'salvage_value',
      label: 'Salvage / Residual Value',
      type: 'number',
      required: false,
      description: 'Estimated scrap or disposal residual value at end of useful life.',
      aliases: ['residual_value', 'scrap_value', 'salvage'],
    },
    {
      key: 'depreciation_method',
      label: 'Depreciation Method',
      type: 'enum',
      required: false,
      options: ['straight_line', 'declining_balance', 'none'],
      description: 'Depreciation method: straight_line, declining_balance, or none.',
      aliases: ['method', 'dep_method', 'depreciation_type'],
    },
    {
      key: 'useful_life_years',
      label: 'Useful Life (Years)',
      type: 'number',
      required: false,
      description: 'Expected operational lifespan in years (e.g. 5, 7, 10).',
      aliases: ['useful_life', 'lifespan_years', 'life_years', 'years'],
    },
    {
      key: 'status',
      label: 'Asset Status',
      type: 'enum',
      required: false,
      options: ['in_use', 'active', 'under_maintenance', 'idle', 'disposed'],
      description: 'Current operational state: in_use, active, under_maintenance, idle, or disposed.',
      aliases: ['operational_status', 'condition_status', 'state'],
    },
    {
      key: 'serial_number',
      label: 'Serial Number',
      type: 'string',
      required: false,
      description: 'Manufacturer chassis or OEM serial number.',
      aliases: ['serial_no', 'serial', 'chassis_no', 'oem_serial'],
    },
    {
      key: 'model',
      label: 'Model / Variant',
      type: 'string',
      required: false,
      description: 'Equipment model or specification variant.',
      aliases: ['model_number', 'model_no', 'variant'],
    },
    {
      key: 'manufacturer',
      label: 'Manufacturer / Brand',
      type: 'string',
      required: false,
      description: 'OEM maker or machinery manufacturer brand.',
      aliases: ['brand', 'maker', 'vendor'],
    },
  ],
  sampleRows: [
    {
      asset_code: 'AST-MC-001',
      name: 'High-Speed 4-Needle Industrial Embroidery Machine',
      category: 'Machinery & Equipment',
      purchase_date: '2024-06-15',
      purchase_cost: 1850000,
      salvage_value: 150000,
      depreciation_method: 'straight_line',
      useful_life_years: 7,
      status: 'in_use',
      serial_number: 'TAJ-2024-88910',
      model: 'TMAR-KC1204',
      manufacturer: 'Tajima',
    },
    {
      asset_code: 'AST-VEH-002',
      name: '3-Ton Delivery Truck - Refrigerated',
      category: 'Vehicles',
      purchase_date: '2025-01-20',
      purchase_cost: 3200000,
      salvage_value: 500000,
      depreciation_method: 'straight_line',
      useful_life_years: 5,
      status: 'in_use',
      serial_number: 'ISZ-NPR-2025',
      model: 'NPR 75',
      manufacturer: 'Isuzu',
    },
    {
      asset_code: 'AST-IT-003',
      name: 'Factory Production Central Server Rack',
      category: 'IT Hardware',
      purchase_date: '2025-09-10',
      purchase_cost: 650000,
      salvage_value: 50000,
      depreciation_method: 'straight_line',
      useful_life_years: 3,
      status: 'in_use',
      serial_number: 'DELL-R750-X19',
      model: 'PowerEdge R750',
      manufacturer: 'Dell',
    },
  ],
};
