import type { ImportSchemaConfig } from '../../../components/import/types';

export const openingJournalImportSchema: ImportSchemaConfig = {
  entityTitle: 'Opening Journal Entries',
  templateFileName: 'erp_opening_journal_import_template',
  uniqueIdentifierKey: 'entry_number',
  supportsUpsert: true,
  apiEndpoint: '/finance/journal-entries/bulk-import',
  columns: [
    {
      key: 'entry_number',
      label: 'Journal Entry / Voucher #',
      type: 'string',
      required: false,
      description: 'Voucher number or reference. Lines sharing the same voucher number are grouped into one journal voucher.',
      aliases: ['voucher_no', 'reference', 'journal_number', 'entry_no', 'doc_number', 'ref_no'],
    },
    {
      key: 'entry_date',
      label: 'Entry Date',
      type: 'date',
      required: true,
      description: 'Effective posting date (YYYY-MM-DD).',
      aliases: ['date', 'posting_date', 'effective_date', 'txn_date', 'voucher_date'],
    },
    {
      key: 'account_code',
      label: 'GL Account Code',
      type: 'string',
      required: true,
      description: 'Account code from Chart of Accounts (e.g. 1010, 2010).',
      aliases: ['account', 'gl_code', 'account_number', 'acc_code', 'ac_code'],
    },
    {
      key: 'debit_amount',
      label: 'Debit Amount',
      type: 'number',
      required: false,
      description: 'Debit amount in local currency (leave 0 if credit).',
      aliases: ['debit', 'dr', 'dr_amount', 'amount_dr'],
    },
    {
      key: 'credit_amount',
      label: 'Credit Amount',
      type: 'number',
      required: false,
      description: 'Credit amount in local currency (leave 0 if debit).',
      aliases: ['credit', 'cr', 'cr_amount', 'amount_cr'],
    },
    {
      key: 'description',
      label: 'Line Description / Narration',
      type: 'string',
      required: false,
      description: 'Memo, remark, or narration for this line entry.',
      aliases: ['narration', 'memo', 'remarks', 'particulars', 'notes'],
    },
  ],
  sampleRows: [
    {
      entry_number: 'JE-OPEN-2026',
      entry_date: '2026-01-01',
      account_code: '1010',
      debit_amount: 250000,
      credit_amount: 0,
      description: 'Opening Cash on Hand',
    },
    {
      entry_number: 'JE-OPEN-2026',
      entry_date: '2026-01-01',
      account_code: '1020',
      debit_amount: 1500000,
      credit_amount: 0,
      description: 'Opening Bank Balances',
    },
    {
      entry_number: 'JE-OPEN-2026',
      entry_date: '2026-01-01',
      account_code: '2010',
      debit_amount: 0,
      credit_amount: 450000,
      description: 'Opening Accounts Payable',
    },
    {
      entry_number: 'JE-OPEN-2026',
      entry_date: '2026-01-01',
      account_code: '3010',
      debit_amount: 0,
      credit_amount: 1300000,
      description: 'Opening Retained Earnings / Equity',
    },
  ],
};
