import type { ImportSchemaConfig } from '../../../components/import/types';

export const qcParameterImportSchema: ImportSchemaConfig = {
  entityTitle: 'Quality Control (QC) Parameters',
  templateFileName: 'erp_qc_parameters_import_template',
  uniqueIdentifierKey: 'name',
  supportsUpsert: true,
  apiEndpoint: '/qc/parameters/bulk-import',
  columns: [
    {
      key: 'name',
      label: 'Parameter Name',
      required: true,
      type: 'string',
      sampleValue: 'Tensile Strength',
      description: 'Standard inspection metric or test specification title',
      aliases: ['name', 'parameter_name', 'parameter', 'qc_parameter', 'title', 'test_name', 'metric_name'],
    },
    {
      key: 'product_sku',
      label: 'Applicable Product SKU',
      required: false,
      type: 'string',
      sampleValue: 'PRD-RAW-001',
      description: 'Leave empty to apply as a global facility parameter, or specify product SKU',
      aliases: ['product_sku', 'sku', 'product_code', 'product', 'item_code'],
    },
    {
      key: 'type',
      label: 'Measurement Type',
      required: false,
      type: 'enum',
      options: ['numeric', 'boolean', 'select', 'text'],
      sampleValue: 'numeric',
      description: 'numeric, boolean, select, or text (default: numeric)',
      aliases: ['type', 'parameter_type', 'data_type', 'metric_type'],
    },
    {
      key: 'min_value',
      label: 'Minimum Tolerance Limit',
      required: false,
      type: 'number',
      sampleValue: 10.5,
      description: 'Lower acceptable bound for numeric measurements',
      aliases: ['min_value', 'min', 'lower_limit', 'minimum_tolerance', 'minimum', 'lower_bound'],
    },
    {
      key: 'max_value',
      label: 'Maximum Tolerance Limit',
      required: false,
      type: 'number',
      sampleValue: 25.0,
      description: 'Upper acceptable bound for numeric measurements',
      aliases: ['max_value', 'max', 'upper_limit', 'maximum_tolerance', 'maximum', 'upper_bound'],
    },
    {
      key: 'unit_code',
      label: 'Metric Unit of Measure',
      required: false,
      type: 'string',
      sampleValue: 'KG',
      description: 'Measurement unit code (e.g. KG, MM, PSI, CELSIUS)',
      aliases: ['unit_code', 'unit', 'uom', 'unit_name'],
    },
    {
      key: 'is_mandatory',
      label: 'Mandatory Inspection Flag',
      required: false,
      type: 'boolean',
      sampleValue: true,
      description: 'Whether passing this test is required for batch release (default: true)',
      aliases: ['is_mandatory', 'mandatory', 'required', 'strict', 'blocking'],
    },
    {
      key: 'sort_order',
      label: 'Display / Inspection Order',
      required: false,
      type: 'number',
      sampleValue: 1,
      description: 'Sequence priority on inspection work-sheets (default: 0)',
      aliases: ['sort_order', 'order', 'priority', 'sort', 'sequence'],
    },
  ],
};
