import type { ReportDefinition, ReportDataResponse } from '../../types/api/reports';

export interface ModuleCategory {
  id: string;
  name: string;
  shortName: string;
  iconName: string;
  description: string;
  badgeTone: string;
}

export const REPORT_MODULES: ModuleCategory[] = [
  {
    id: 'all',
    name: 'All Modules',
    shortName: 'All',
    iconName: 'Layers',
    description: 'Comprehensive enterprise reporting across all operations.',
    badgeTone: 'bg-indigo-50 text-indigo-700 border-indigo-200',
  },
  {
    id: 'production',
    name: 'Production & Manufacturing',
    shortName: 'Production',
    iconName: 'Factory',
    description: 'Output yield, batch run-rates, scrap ratios, and worker piece rates.',
    badgeTone: 'bg-blue-50 text-blue-700 border-blue-200',
  },
  {
    id: 'inventory',
    name: 'Inventory & Warehouse',
    shortName: 'Inventory',
    iconName: 'Boxes',
    description: 'Stock valuation, ledger movements, safety stock alerts, and transfers.',
    badgeTone: 'bg-emerald-50 text-emerald-700 border-emerald-200',
  },
  {
    id: 'purchasing',
    name: 'Purchase & Procurement',
    shortName: 'Purchasing',
    iconName: 'ShoppingBag',
    description: 'PO status, supplier lead times, GRN inspection, and accounts payable.',
    badgeTone: 'bg-amber-50 text-amber-700 border-amber-200',
  },
  {
    id: 'sales',
    name: 'Sales & POS Counters',
    shortName: 'Sales & POS',
    iconName: 'Receipt',
    description: 'Omnichannel revenue, counter shifts, split tenders, and sales returns.',
    badgeTone: 'bg-cyan-50 text-cyan-700 border-cyan-200',
  },
  {
    id: 'profit',
    name: 'Profitability & Margins',
    shortName: 'Profitability',
    iconName: 'TrendingUp',
    description: 'Gross margin by SKU, invoice profitability, and net contribution.',
    badgeTone: 'bg-violet-50 text-violet-700 border-violet-200',
  },
  {
    id: 'crm',
    name: 'CRM & Commercial Leads',
    shortName: 'CRM',
    iconName: 'Users',
    description: 'Pipeline funnel, fake lead verification audits, and conversion rates.',
    badgeTone: 'bg-rose-50 text-rose-700 border-rose-200',
  },
  {
    id: 'salesmen',
    name: 'Salesman Targets & Quotas',
    shortName: 'Salesmen',
    iconName: 'Target',
    description: 'Monthly quota tracking, achievement %, profit generated, and tiered incentives.',
    badgeTone: 'bg-orange-50 text-orange-700 border-orange-200',
  },
  {
    id: 'delivery',
    name: 'Delivery & Logistics',
    shortName: 'Delivery',
    iconName: 'Truck',
    description: 'Courier fulfillment (Pathao/Steadfast), RTO returns, and COD settlement.',
    badgeTone: 'bg-sky-50 text-sky-700 border-sky-200',
  },
  {
    id: 'hr',
    name: 'HR & Workforce Payroll',
    shortName: 'HR & Payroll',
    iconName: 'UserCheck',
    description: 'Attendance, piece-rate wages, overtime units, and disbursed net payroll.',
    badgeTone: 'bg-teal-50 text-teal-700 border-teal-200',
  },
  {
    id: 'finance',
    name: 'Finance & Accounts Ledger',
    shortName: 'Finance',
    iconName: 'DollarSign',
    description: 'Trial balance, profit & loss, operating expenses, and AR/AP aging.',
    badgeTone: 'bg-emerald-50 text-emerald-800 border-emerald-200',
  },
  {
    id: 'assets',
    name: 'Fixed Asset Management',
    shortName: 'Assets',
    iconName: 'Cpu',
    description: 'Asset register, net book value (NBV), maintenance logs, and depreciation.',
    badgeTone: 'bg-slate-100 text-slate-700 border-slate-300',
  },
  {
    id: 'qc',
    name: 'QC & Audit Compliance',
    shortName: 'QC & Audit',
    iconName: 'ShieldCheck',
    description: 'AQL 2.5 inspection pass/fail rates, defect tags, and regulatory audit logs.',
    badgeTone: 'bg-purple-50 text-purple-700 border-purple-200',
  },
];

export const ALL_REPORT_DEFINITIONS: ReportDefinition[] = [
  // PRODUCTION
  {
    id: 1,
    uuid: 'rpt-prod-01',
    code: 'daily_production',
    name: 'Daily Production Report',
    module: 'production',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Daily output units planned vs actual produced per line and shift.',
  },
  {
    id: 2,
    uuid: 'rpt-prod-02',
    code: 'monthly_production',
    name: 'Monthly Production Summary',
    module: 'production',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Aggregated monthly production volume, capacity utilization %, and schedule adherence.',
  },
  {
    id: 3,
    uuid: 'rpt-prod-03',
    code: 'production_target_vs_achievement',
    name: 'Production Target vs Achievement',
    module: 'production',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Comparative variance between factory target goals and actual manufactured output.',
  },
  {
    id: 4,
    uuid: 'rpt-prod-04',
    code: 'production_yield',
    name: 'Production Yield & Scrap Analysis',
    module: 'production',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Batch-level yield efficiency %, actual vs planned output, and defect rejection count.',
  },
  {
    id: 5,
    uuid: 'rpt-prod-05',
    code: 'worker_production',
    name: 'Worker Piece-Rate Production Log',
    module: 'production',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Line operator individual output logs, hours worked, and earned piece-rate values.',
  },
  {
    id: 6,
    uuid: 'rpt-prod-06',
    code: 'line_wise_production',
    name: 'Line-wise Production & Bottlenecks',
    module: 'production',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Assembly line efficiency, hourly run rates (pcs/hr), downtime, and bottlenecks.',
  },
  {
    id: 7,
    uuid: 'rpt-prod-07',
    code: 'production_wastage_scrap',
    name: 'Production Wastage, Rework & Scrap',
    module: 'production',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Material wastage logs, rework labor hours, and scrap value write-offs.',
  },

  // INVENTORY
  {
    id: 10,
    uuid: 'rpt-inv-01',
    code: 'stock_valuation',
    name: 'Warehouse Stock Valuation & Aging',
    module: 'inventory',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'On-hand inventory valued at weighted average cost with FIFO aging brackets.',
  },
  {
    id: 11,
    uuid: 'rpt-inv-02',
    code: 'current_stock',
    name: 'Current Stock On-Hand & Levels',
    module: 'inventory',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Live physical stock, reserved quantities, and available units per warehouse.',
  },
  {
    id: 12,
    uuid: 'rpt-inv-03',
    code: 'stock_ledger',
    name: 'Perpetual Stock Ledger',
    module: 'inventory',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Chronological audit trail of all inventory receipts, issues, and adjustments.',
  },
  {
    id: 13,
    uuid: 'rpt-inv-04',
    code: 'low_stock',
    name: 'Low Stock & Reorder Thresholds',
    module: 'inventory',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Items approaching safety stock levels requiring immediate replenishment.',
  },
  {
    id: 14,
    uuid: 'rpt-inv-05',
    code: 'warehouse_transfer',
    name: 'Warehouse Inter-Transfer Log',
    module: 'inventory',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Completed, in-transit, and pending stock transfer notes between facilities.',
  },
  {
    id: 15,
    uuid: 'rpt-inv-06',
    code: 'damaged_stock',
    name: 'Damaged & Written-off Stock',
    module: 'inventory',
    category: 'operational',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Damaged items logged from transit, factory floor, or warehouse accidents.',
  },

  // PURCHASING
  {
    id: 20,
    uuid: 'rpt-pur-01',
    code: 'purchase_summary',
    name: 'Purchase Order (PO) Summary',
    module: 'purchasing',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Overview of open, partially received, closed, and cancelled purchase orders.',
  },
  {
    id: 21,
    uuid: 'rpt-pur-02',
    code: 'purchase_details',
    name: 'Purchase Details & GRN Log',
    module: 'purchasing',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Goods Receipt Notes (GRN) with received quantities and inspection status.',
  },
  {
    id: 22,
    uuid: 'rpt-pur-03',
    code: 'supplier_due',
    name: 'Supplier Payables & Aging Ledger',
    module: 'purchasing',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Outstanding supplier balances categorized by 0-30, 31-60, 61-90, 90+ days aging.',
  },

  // SALES & POS
  {
    id: 30,
    uuid: 'rpt-sls-01',
    code: 'sales_performance',
    name: 'Channel Sales & Revenue Ledger',
    module: 'sales',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Order volume, gross sales revenue, applied discounts, and payment settlement.',
  },
  {
    id: 31,
    uuid: 'rpt-sls-02',
    code: 'daily_sales',
    name: 'Daily Sales & Revenue Ledger',
    module: 'sales',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Daily order volume, gross receipts, applied discounts, and net collected revenue.',
  },
  {
    id: 32,
    uuid: 'rpt-sls-03',
    code: 'pos_counter_sales',
    name: 'POS Counter Shift & Tender Reconciliation',
    module: 'sales',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Shift opening cash, cash sales, card payments, mobile banking, and variance.',
  },
  {
    id: 33,
    uuid: 'rpt-sls-04',
    code: 'b2b_sales',
    name: 'B2B Wholesale Sales Ledger',
    module: 'sales',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Bulk wholesale order volume, invoice balances, and institutional payment terms.',
  },
  {
    id: 34,
    uuid: 'rpt-sls-05',
    code: 'sales_return',
    name: 'Sales Returns & Credit Notes',
    module: 'sales',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Customer return items, return reasons, refund types, and restocked units.',
  },

  // PROFITABILITY
  {
    id: 40,
    uuid: 'rpt-prf-01',
    code: 'invoice_profit',
    name: 'Invoice-wise Gross Profit Analysis',
    module: 'profit',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Individual commercial invoices analyzed by sales price minus COGS.',
  },
  {
    id: 41,
    uuid: 'rpt-prf-02',
    code: 'product_profit',
    name: 'Product-wise Profit & Gross Margin %',
    module: 'profit',
    category: 'analytical',
    tier: 'hourly',
    supports_export: true,
    is_active: true,
    description: 'Gross margin ranking and contribution percentage calculated across catalog.',
  },

  // CRM & LEADS
  {
    id: 50,
    uuid: 'rpt-crm-01',
    code: 'lead_summary',
    name: 'Commercial Lead Pipeline Summary',
    module: 'crm',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Total leads across pipeline stages: New, Contacted, Qualified, Converted, Lost.',
  },
  {
    id: 51,
    uuid: 'rpt-crm-02',
    code: 'fake_leads_audit',
    name: 'Fake & Invalid Lead Verification Audit',
    module: 'crm',
    category: 'compliance',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Audit log of unverified, unreachable, or flagged fraudulent customer inquiries.',
  },
  {
    id: 52,
    uuid: 'rpt-crm-03',
    code: 'conversion_rate_source',
    name: 'Lead Conversion Rate by Source',
    module: 'crm',
    category: 'analytical',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Conversion efficiency calculated across Facebook, Storefront, WhatsApp, and Walk-ins.',
  },

  // SALESMEN
  {
    id: 60,
    uuid: 'rpt-rep-01',
    code: 'salesman_quota_achievement',
    name: 'Salesman Monthly Quota vs Achievement',
    module: 'salesmen',
    category: 'executive',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Assigned monthly targets (৳) vs achieved revenue and completion percentage.',
  },
  {
    id: 61,
    uuid: 'rpt-rep-02',
    code: 'salesman_remaining_target',
    name: 'Salesman Remaining Target & Shortfall',
    module: 'salesmen',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Pending sales shortfall required for each salesman to meet monthly quotas.',
  },
  {
    id: 62,
    uuid: 'rpt-rep-03',
    code: 'salesman_incentive_accrual',
    name: 'Salesman Tiered Incentive Accrual',
    module: 'salesmen',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Tiered commission calculations, approved bonuses, and pending disbursements.',
  },
  {
    id: 63,
    uuid: 'rpt-rep-04',
    code: 'salesman_leaderboard',
    name: 'Sales Representative Leaderboard',
    module: 'salesmen',
    category: 'analytical',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Ranked performance metrics across sales reps by conversion rate, profit, and volume.',
  },

  // DELIVERY
  {
    id: 70,
    uuid: 'rpt-del-01',
    code: 'pending_deliveries',
    name: 'Pending Deliveries & Dispatch Queue',
    module: 'delivery',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Parcels packaged and staged for courier pickup or vehicle loading.',
  },
  {
    id: 71,
    uuid: 'rpt-del-02',
    code: 'delivered_orders',
    name: 'Delivered Shipments & POD Log',
    module: 'delivery',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Successfully completed shipments with Proof of Delivery (POD) confirmations.',
  },
  {
    id: 72,
    uuid: 'rpt-del-03',
    code: 'courier_performance',
    name: 'Courier Performance (Pathao/Steadfast)',
    module: 'delivery',
    category: 'analytical',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Courier success rate %, average delivery transit time, and SLA performance.',
  },
  {
    id: 73,
    uuid: 'rpt-del-04',
    code: 'cod_reconciliation',
    name: 'Cash On Delivery (COD) Reconciliation',
    module: 'delivery',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Courier collected cash reconciliation vs actual bank deposits received.',
  },

  // HR & PAYROLL
  {
    id: 80,
    uuid: 'rpt-hr-01',
    code: 'payroll_summary',
    name: 'Disbursed Payroll Register & Net Pay',
    module: 'hr',
    category: 'compliance',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Aggregated gross earnings, piece-rate bonuses, deductions, and net payouts.',
  },
  {
    id: 81,
    uuid: 'rpt-hr-02',
    code: 'daily_attendance',
    name: 'Daily & Monthly Attendance Log',
    module: 'hr',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Daily check-in, late arrival records, early departures, and approved leaves.',
  },
  {
    id: 82,
    uuid: 'rpt-hr-03',
    code: 'sales_commission_payout',
    name: 'Sales Commission & Incentive Payouts',
    module: 'hr',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Approved commercial sales incentives transferred to payroll disbursement.',
  },

  // FINANCE & ACCOUNTS
  {
    id: 90,
    uuid: 'rpt-fin-01',
    code: 'gl_summary',
    name: 'General Ledger Summary Trial Balance',
    module: 'finance',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Debit and credit balance reconciliation across all active GL accounts.',
  },
  {
    id: 91,
    uuid: 'rpt-fin-02',
    code: 'customer_ar_aging',
    name: 'Customer Receivables (AR) Aging (0-90+ Days)',
    module: 'finance',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Outstanding B2B trade receivables categorized by 0-30, 31-60, 61-90, 90+ days.',
  },
  {
    id: 92,
    uuid: 'rpt-fin-03',
    code: 'operating_expenses',
    name: 'Operating Expense Breakdown by Category',
    module: 'finance',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Factory overhead, power/utilities, logistics fees, rent, and administration.',
  },
  {
    id: 93,
    uuid: 'rpt-fin-04',
    code: 'cash_bank_ledger',
    name: 'Cash & Bank Accounts Ledger',
    module: 'finance',
    category: 'financial',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Balances across all company bank accounts, petty cash, and payment gateways.',
  },

  // ASSETS
  {
    id: 100,
    uuid: 'rpt-ast-01',
    code: 'fixed_asset_register',
    name: 'Fixed Asset Register & Inventory',
    module: 'assets',
    category: 'compliance',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Comprehensive register of factory machinery, cutting tables, vehicles, and IT.',
  },
  {
    id: 101,
    uuid: 'rpt-ast-02',
    code: 'asset_valuation_nbv',
    name: 'Asset Valuation & Net Book Value (NBV)',
    module: 'assets',
    category: 'financial',
    tier: 'daily',
    supports_export: true,
    is_active: true,
    description: 'Asset acquisition cost, cumulative depreciation, and current book valuation.',
  },
  {
    id: 102,
    uuid: 'rpt-ast-03',
    code: 'asset_maintenance_log',
    name: 'Asset Maintenance, Repairs & Downtime',
    module: 'assets',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Preventive maintenance history, emergency breakdown repairs, and parts replacement.',
  },

  // QC & AUDIT
  {
    id: 110,
    uuid: 'rpt-qc-01',
    code: 'qc_inspection_ratio',
    name: 'QC Inspection Pass / Fail Ratios',
    module: 'qc',
    category: 'compliance',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Quality pass rates and defect percentage evaluated against AQL 2.5 standards.',
  },
  {
    id: 111,
    uuid: 'rpt-qc-02',
    code: 'defect_categorization',
    name: 'Defect Categorization (Critical/Major/Minor)',
    module: 'qc',
    category: 'operational',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Categorization of stitching flaws, oil stains, measurement faults, and runs.',
  },
  {
    id: 112,
    uuid: 'rpt-qc-03',
    code: 'compliance_audit_trail',
    name: 'System Compliance & Transaction Audit Trail',
    module: 'qc',
    category: 'compliance',
    tier: 'live',
    supports_export: true,
    is_active: true,
    description: 'Security and financial audit trail of critical operational actions.',
  },
];

// Tailored fallback datasets for all core report categories
export const REPORT_FALLBACK_DATA: Record<string, ReportDataResponse> = {
  // 1. Production Yield
  production_yield: {
    columns: {
      batch_number: { label: 'Batch Number', type: 'string', sortable: true },
      product_name: { label: 'Product / SKU', type: 'string' },
      batch_date: { label: 'Batch Date', type: 'date', sortable: true },
      planned_quantity: { label: 'Planned Qty', type: 'number' },
      actual_quantity: { label: 'Produced Qty', type: 'number' },
      rejected_quantity: { label: 'Wastage', type: 'number' },
      yield_percentage: { label: 'Yield Efficiency', type: 'percentage' },
      status: { label: 'Status', type: 'badge' },
    },
    data: [
      {
        batch_number: 'BAT-202608-001',
        product_name: 'Cotton Crew T-Shirt (TSH-001)',
        batch_date: '2026-08-28',
        planned_quantity: '1,000.00',
        actual_quantity: '980.00',
        rejected_quantity: '20.00',
        yield_percentage: '98.00%',
        status: 'completed',
      },
      {
        batch_number: 'BAT-202608-002',
        product_name: 'Denim Slim Jeans (JNS-002)',
        batch_date: '2026-08-27',
        planned_quantity: '500.00',
        actual_quantity: '492.00',
        rejected_quantity: '8.00',
        yield_percentage: '98.40%',
        status: 'completed',
      },
      {
        batch_number: 'BAT-202608-003',
        product_name: 'Fleece Hoodie (HOD-003)',
        batch_date: '2026-08-26',
        planned_quantity: '750.00',
        actual_quantity: '730.00',
        rejected_quantity: '20.00',
        yield_percentage: '97.33%',
        status: 'in_progress',
      },
    ],
    summary: {
      total_batches: 3,
      total_planned_quantity: '2,250.00',
      total_actual_quantity: '2,202.00',
      average_yield_percentage: '97.87%',
    },
    pagination: { total: 3, current_page: 1, per_page: 25, last_page: 1 },
    meta: { freshness: { as_of: new Date().toISOString(), tier: 'live', stale: false } },
  },

  // 2. Stock Valuation
  stock_valuation: {
    columns: {
      sku: { label: 'Item Code', type: 'string', sortable: true },
      product_name: { label: 'Item Description', type: 'string' },
      warehouse_name: { label: 'Warehouse / Facility', type: 'string' },
      quantity_on_hand: { label: 'On-Hand Stock', type: 'number' },
      unit_cost: { label: 'Unit Cost', type: 'currency' },
      total_valuation: { label: 'Total Valuation', type: 'currency' },
      aging_days: { label: 'Aging (Days)', type: 'number' },
      health_status: { label: 'Stock Status', type: 'badge' },
    },
    data: [
      {
        sku: 'TSH-001',
        product_name: 'Cotton Crew T-Shirt (M / Navy)',
        warehouse_name: 'Central Factory Hub',
        quantity_on_hand: '480.00',
        unit_cost: '320.00',
        total_valuation: '153600.00',
        aging_days: '14',
        health_status: 'in_stock',
      },
      {
        sku: 'JNS-002',
        product_name: 'Denim Slim Jeans (32 / Blue)',
        warehouse_name: 'Gulshan Flagship Store',
        quantity_on_hand: '120.00',
        unit_cost: '850.00',
        total_valuation: '102000.00',
        aging_days: '22',
        health_status: 'in_stock',
      },
      {
        sku: 'RAW-FAB-01',
        product_name: '100% Combed Cotton Yarn (Kg)',
        warehouse_name: 'Raw Material Depot',
        quantity_on_hand: '2,500.00',
        unit_cost: '180.00',
        total_valuation: '450000.00',
        aging_days: '8',
        health_status: 'in_stock',
      },
    ],
    summary: {
      total_skus: 3,
      total_units_on_hand: '3,100.00',
      total_valuation: '705,600.00',
      active_warehouses: 3,
    },
    pagination: { total: 3, current_page: 1, per_page: 25, last_page: 1 },
    meta: { freshness: { as_of: new Date().toISOString(), tier: 'live', stale: false } },
  },

  // 3. Sales Performance / Omnichannel
  sales_performance: {
    columns: {
      order_number: { label: 'Order / Invoice #', type: 'string', sortable: true },
      order_date: { label: 'Date', type: 'date', sortable: true },
      channel: { label: 'Channel', type: 'badge' },
      customer_name: { label: 'Customer / Entity', type: 'string' },
      subtotal: { label: 'Subtotal', type: 'currency' },
      tax_amount: { label: 'Tax', type: 'currency' },
      grand_total: { label: 'Grand Total', type: 'currency' },
      payment_status: { label: 'Status', type: 'badge' },
    },
    data: [
      {
        order_number: 'POS-INV-20260906-001',
        order_date: '2026-09-06',
        channel: 'pos',
        customer_name: 'Walk-in Counter Customer',
        subtotal: '1250.00',
        tax_amount: '62.50',
        grand_total: '1312.50',
        payment_status: 'paid',
      },
      {
        order_number: 'SO-202609-B2B-042',
        order_date: '2026-09-05',
        channel: 'b2b',
        customer_name: 'Apex Retail Enterprises',
        subtotal: '148000.00',
        tax_amount: '7400.00',
        grand_total: '155400.00',
        payment_status: 'paid',
      },
      {
        order_number: 'ECO-ORD-202609-019',
        order_date: '2026-09-06',
        channel: 'storefront',
        customer_name: 'Farhana Rahman',
        subtotal: '2450.00',
        tax_amount: '122.50',
        grand_total: '2572.50',
        payment_status: 'completed',
      },
    ],
    summary: {
      total_orders: 3,
      total_subtotal: '151,700.00',
      total_tax: '7,585.00',
      total_revenue: '159,285.00',
    },
    pagination: { total: 3, current_page: 1, per_page: 25, last_page: 1 },
    meta: { freshness: { as_of: new Date().toISOString(), tier: 'live', stale: false } },
  },

  // 4. POS Counter Sales & Tender Reconciliation
  pos_counter_sales: {
    columns: {
      session_id: { label: 'Shift Session', type: 'string', sortable: true },
      terminal: { label: 'Terminal / Counter', type: 'string' },
      cashier: { label: 'Cashier Operator', type: 'string' },
      cash_tendered: { label: 'Cash (BDT)', type: 'currency' },
      card_tendered: { label: 'POS Card (BDT)', type: 'currency' },
      mobile_tendered: { label: 'bKash/Nagad (BDT)', type: 'currency' },
      total_tendered: { label: 'Shift Gross (BDT)', type: 'currency' },
      shift_status: { label: 'Status', type: 'badge' },
    },
    data: [
      {
        session_id: 'SES-202608-001',
        terminal: 'TRM-01 (Gulshan Flagship)',
        cashier: 'Sadia Jahan',
        cash_tendered: '18500.00',
        card_tendered: '12400.00',
        mobile_tendered: '8600.00',
        total_tendered: '39500.00',
        shift_status: 'open',
      },
      {
        session_id: 'SES-202608-002',
        terminal: 'TRM-02 (Uttara Counter)',
        cashier: 'Tanvir Ahmed',
        cash_tendered: '14200.00',
        card_tendered: '9800.00',
        mobile_tendered: '5400.00',
        total_tendered: '29400.00',
        shift_status: 'closed',
      },
    ],
    summary: {
      total_sessions: 2,
      total_cash: '32,700.00',
      total_digital: '36,200.00',
      total_pos_volume: '68,900.00',
    },
    pagination: { total: 2, current_page: 1, per_page: 25, last_page: 1 },
    meta: { freshness: { as_of: new Date().toISOString(), tier: 'live', stale: false } },
  },

  // 5. Salesman Quota & Target Achievement
  salesman_quota_achievement: {
    columns: {
      salesman_code: { label: 'Emp ID', type: 'string', sortable: true },
      salesman_name: { label: 'Sales Representative', type: 'string' },
      target_bdt: { label: 'Monthly Quota', type: 'currency' },
      achieved_bdt: { label: 'Achieved Sales', type: 'currency' },
      achievement_pct: { label: 'Achievement %', type: 'percentage' },
      profit_generated: { label: 'Profit Delivered', type: 'currency' },
      incentive_earned: { label: 'Incentive Accrued', type: 'currency' },
      status: { label: 'Quota Status', type: 'badge' },
    },
    data: [
      {
        salesman_code: 'EMP-SLS-01',
        salesman_name: 'Rafiqul Islam',
        target_bdt: '1000000.00',
        achieved_bdt: '720000.00',
        achievement_pct: '72.00%',
        profit_generated: '185000.00',
        incentive_earned: '12500.00',
        status: 'in_progress',
      },
      {
        salesman_code: 'EMP-SLS-02',
        salesman_name: 'Kamal Hossain',
        target_bdt: '800000.00',
        achieved_bdt: '890000.00',
        achievement_pct: '111.25%',
        profit_generated: '240000.00',
        incentive_earned: '22000.00',
        status: 'completed',
      },
      {
        salesman_code: 'EMP-SLS-03',
        salesman_name: 'Nasreen Sultana',
        target_bdt: '1200000.00',
        achieved_bdt: '650000.00',
        achievement_pct: '54.17%',
        profit_generated: '160000.00',
        incentive_earned: '6500.00',
        status: 'in_progress',
      },
    ],
    summary: {
      total_sales_reps: 3,
      total_target_quota: '3,000,000.00',
      total_achieved_sales: '2,260,000.00',
      total_incentive_accrued: '41,000.00',
    },
    pagination: { total: 3, current_page: 1, per_page: 25, last_page: 1 },
    meta: { freshness: { as_of: new Date().toISOString(), tier: 'live', stale: false } },
  },

  // 6. CRM & Lead Pipeline
  lead_summary: {
    columns: {
      lead_code: { label: 'Lead Ref', type: 'string', sortable: true },
      contact_name: { label: 'Client / Contact', type: 'string' },
      source: { label: 'Source Channel', type: 'badge' },
      salesman: { label: 'Assigned Salesman', type: 'string' },
      estimated_value: { label: 'Deal Potential', type: 'currency' },
      stage: { label: 'Pipeline Stage', type: 'badge' },
      verification: { label: 'Audit Status', type: 'badge' },
    },
    data: [
      {
        lead_code: 'LD-202609-001',
        contact_name: 'Green Valley Garments',
        source: 'facebook_ad',
        salesman: 'Rafiqul Islam',
        estimated_value: '350000.00',
        stage: 'qualified',
        verification: 'valid',
      },
      {
        lead_code: 'LD-202609-002',
        contact_name: 'Spam Auto-Inquiry',
        source: 'storefront',
        salesman: 'Unassigned',
        estimated_value: '0.00',
        stage: 'lost',
        verification: 'fake',
      },
      {
        lead_code: 'LD-202609-003',
        contact_name: 'Metro Fashion Corp',
        source: 'whatsapp',
        salesman: 'Kamal Hossain',
        estimated_value: '520000.00',
        stage: 'converted',
        verification: 'valid',
      },
    ],
    summary: {
      total_pipeline_leads: 3,
      valid_leads_count: 2,
      fake_leads_intercepted: 1,
      conversion_rate: '66.67%',
    },
    pagination: { total: 3, current_page: 1, per_page: 25, last_page: 1 },
    meta: { freshness: { as_of: new Date().toISOString(), tier: 'live', stale: false } },
  },

  // 7. Delivery & Courier Fulfillment
  courier_performance: {
    columns: {
      courier_partner: { label: 'Courier Partner', type: 'badge', sortable: true },
      total_dispatched: { label: 'Dispatched Orders', type: 'number' },
      delivered_count: { label: 'Delivered', type: 'number' },
      returned_rto: { label: 'Returned (RTO)', type: 'number' },
      delivery_success_pct: { label: 'Success Rate', type: 'percentage' },
      cod_collected: { label: 'COD Remitted', type: 'currency' },
      avg_sla_hours: { label: 'Avg SLA (Hrs)', type: 'number' },
    },
    data: [
      {
        courier_partner: 'Pathao Courier',
        total_dispatched: '450',
        delivered_count: '425',
        returned_rto: '25',
        delivery_success_pct: '94.44%',
        cod_collected: '685000.00',
        avg_sla_hours: '24',
      },
      {
        courier_partner: 'Steadfast Courier',
        total_dispatched: '320',
        delivered_count: '298',
        returned_rto: '22',
        delivery_success_pct: '93.12%',
        cod_collected: '412000.00',
        avg_sla_hours: '36',
      },
      {
        courier_partner: 'In-House Fleet',
        total_dispatched: '115',
        delivered_count: '114',
        returned_rto: '1',
        delivery_success_pct: '99.13%',
        cod_collected: '890000.00',
        avg_sla_hours: '12',
      },
    ],
    summary: {
      total_shipments: '885',
      overall_delivery_rate: '94.58%',
      total_cod_collected: '1,987,000.00',
      active_couriers: 3,
    },
    pagination: { total: 3, current_page: 1, per_page: 25, last_page: 1 },
    meta: { freshness: { as_of: new Date().toISOString(), tier: 'live', stale: false } },
  },

  // 8. General Ledger Trial Balance
  gl_summary: {
    columns: {
      account_code: { label: 'GL Account #', type: 'string', sortable: true },
      account_name: { label: 'Account Classification', type: 'string' },
      account_type: { label: 'Account Type', type: 'badge' },
      debit_bdt: { label: 'Debit', type: 'currency' },
      credit_bdt: { label: 'Credit', type: 'currency' },
      balance_bdt: { label: 'Net Balance', type: 'currency' },
    },
    data: [
      {
        account_code: '1010-CASH',
        account_name: 'Petty Cash & Store Registers',
        account_type: 'asset',
        debit_bdt: '125000.00',
        credit_bdt: '45000.00',
        balance_bdt: '80000.00',
      },
      {
        account_code: '1020-BANK',
        account_name: 'City Bank Corporate Account',
        account_type: 'asset',
        debit_bdt: '2450000.00',
        credit_bdt: '890000.00',
        balance_bdt: '1560000.00',
      },
      {
        account_code: '4010-SALES',
        account_name: 'Omnichannel Apparel Sales Revenue',
        account_type: 'income',
        debit_bdt: '0.00',
        credit_bdt: '3250000.00',
        balance_bdt: '3250000.00',
      },
    ],
    summary: {
      total_debit: '2,575,000.00',
      total_credit: '4,185,000.00',
      net_equity_position: '1,610,000.00',
      reconciliation_status: 'balanced',
    },
    pagination: { total: 3, current_page: 1, per_page: 25, last_page: 1 },
    meta: { freshness: { as_of: new Date().toISOString(), tier: 'live', stale: false } },
  },

  // 9. Disbursed Payroll Summary
  payroll_summary: {
    columns: {
      employee_code: { label: 'Employee ID', type: 'string', sortable: true },
      full_name: { label: 'Staff Member', type: 'string' },
      department: { label: 'Department', type: 'string' },
      basic_salary: { label: 'Base Wage', type: 'currency' },
      piece_rate_bonus: { label: 'Piece Bonus', type: 'currency' },
      deductions: { label: 'Deductions', type: 'currency' },
      net_pay: { label: 'Net Disbursed', type: 'currency' },
      disbursement_status: { label: 'Status', type: 'badge' },
    },
    data: [
      {
        employee_code: 'EMP-FAC-012',
        full_name: 'Mohammad Al-Amin',
        department: 'Production Sewing Line A',
        basic_salary: '18500.00',
        piece_rate_bonus: '4200.00',
        deductions: '500.00',
        net_pay: '22200.00',
        disbursement_status: 'posted',
      },
      {
        employee_code: 'EMP-SLS-002',
        full_name: 'Kamal Hossain',
        department: 'Showroom Commercial Sales',
        basic_salary: '25000.00',
        piece_rate_bonus: '22000.00',
        deductions: '1200.00',
        net_pay: '45800.00',
        disbursement_status: 'posted',
      },
      {
        employee_code: 'EMP-LOG-004',
        full_name: 'Zahangir Alam',
        department: 'Warehouse & Dispatch Hub',
        basic_salary: '16000.00',
        piece_rate_bonus: '1500.00',
        deductions: '0.00',
        net_pay: '17500.00',
        disbursement_status: 'posted',
      },
    ],
    summary: {
      total_employees_paid: 3,
      gross_disbursement: '87,200.00',
      total_piece_bonuses: '27,700.00',
      net_payout_total: '85,500.00',
    },
    pagination: { total: 3, current_page: 1, per_page: 25, last_page: 1 },
    meta: { freshness: { as_of: new Date().toISOString(), tier: 'live', stale: false } },
  },

  // 10. Fixed Asset Register
  fixed_asset_register: {
    columns: {
      asset_tag: { label: 'Asset Tag #', type: 'string', sortable: true },
      asset_name: { label: 'Asset Description', type: 'string' },
      category: { label: 'Classification', type: 'string' },
      assigned_to: { label: 'Assigned Location', type: 'string' },
      purchase_cost: { label: 'Acquisition Cost', type: 'currency' },
      net_book_value: { label: 'Net Book Value', type: 'currency' },
      status: { label: 'Operational Health', type: 'badge' },
    },
    data: [
      {
        asset_tag: 'AST-SEW-001',
        asset_name: 'Juki High-Speed Industrial Sewing Machine',
        category: 'Machinery',
        assigned_to: 'Assembly Line Alpha',
        purchase_cost: '65000.00',
        net_book_value: '52000.00',
        status: 'operational',
      },
      {
        asset_tag: 'AST-CUT-004',
        asset_name: 'Eastman Laser Fabric Cutting Table',
        category: 'Machinery',
        assigned_to: 'Cutting Line Beta',
        purchase_cost: '320000.00',
        net_book_value: '275000.00',
        status: 'operational',
      },
      {
        asset_tag: 'AST-GEN-002',
        asset_name: 'Cummins 150kVA Standby Diesel Generator',
        category: 'Utilities',
        assigned_to: 'Central Power Station',
        purchase_cost: '1200000.00',
        net_book_value: '980000.00',
        status: 'operational',
      },
    ],
    summary: {
      total_active_assets: 3,
      total_asset_cost: '1,585,000.00',
      net_book_value_total: '1,307,000.00',
      operational_ratio: '100%',
    },
    pagination: { total: 3, current_page: 1, per_page: 25, last_page: 1 },
    meta: { freshness: { as_of: new Date().toISOString(), tier: 'live', stale: false } },
  },

  // 11. QC Inspection Pass/Fail
  qc_inspection_ratio: {
    columns: {
      inspection_ref: { label: 'QC Audit #', type: 'string', sortable: true },
      batch_number: { label: 'Batch Ref', type: 'string' },
      product_name: { label: 'Inspected Garment', type: 'string' },
      sample_size: { label: 'Sample Pcs', type: 'number' },
      defects_found: { label: 'Defects', type: 'number' },
      pass_rate_pct: { label: 'Pass Rate', type: 'percentage' },
      aql_result: { label: 'AQL 2.5 Audit', type: 'badge' },
    },
    data: [
      {
        inspection_ref: 'QC-202608-011',
        batch_number: 'BAT-202608-001',
        product_name: 'Cotton Crew T-Shirt',
        sample_size: '125',
        defects_found: '2',
        pass_rate_pct: '98.40%',
        aql_result: 'passed',
      },
      {
        inspection_ref: 'QC-202608-012',
        batch_number: 'BAT-202608-002',
        product_name: 'Denim Slim Jeans',
        sample_size: '80',
        defects_found: '1',
        pass_rate_pct: '98.75%',
        aql_result: 'passed',
      },
      {
        inspection_ref: 'QC-202608-013',
        batch_number: 'BAT-202608-003',
        product_name: 'Fleece Hoodie',
        sample_size: '100',
        defects_found: '3',
        pass_rate_pct: '97.00%',
        aql_result: 'passed',
      },
    ],
    summary: {
      inspections_completed: 3,
      average_pass_rate: '98.05%',
      total_defects_caught: 6,
      aql_compliance_rate: '100.00%',
    },
    pagination: { total: 3, current_page: 1, per_page: 25, last_page: 1 },
    meta: { freshness: { as_of: new Date().toISOString(), tier: 'live', stale: false } },
  },
};

/**
 * Returns a tailored fallback report dataset for any report definition code,
 * deriving intelligent structure based on the definition's module if not explicitly defined.
 */
export function getReportFallbackData(code: string, def?: ReportDefinition): ReportDataResponse {
  const existing = REPORT_FALLBACK_DATA[code];
  if (existing) {
    return existing;
  }

  const moduleName = def?.module || 'general';

  // Fallback to closest module representation
  switch (moduleName) {
    case 'production':
      return REPORT_FALLBACK_DATA['production_yield']!;
    case 'inventory':
      return REPORT_FALLBACK_DATA['stock_valuation']!;
    case 'sales':
      return REPORT_FALLBACK_DATA['sales_performance']!;
    case 'pos':
      return REPORT_FALLBACK_DATA['pos_counter_sales']!;
    case 'salesmen':
      return REPORT_FALLBACK_DATA['salesman_quota_achievement']!;
    case 'crm':
      return REPORT_FALLBACK_DATA['lead_summary']!;
    case 'delivery':
      return REPORT_FALLBACK_DATA['courier_performance']!;
    case 'hr':
      return REPORT_FALLBACK_DATA['payroll_summary']!;
    case 'finance':
    case 'profit':
      return REPORT_FALLBACK_DATA['gl_summary']!;
    case 'assets':
      return REPORT_FALLBACK_DATA['fixed_asset_register']!;
    case 'qc':
      return REPORT_FALLBACK_DATA['qc_inspection_ratio']!;
    default:
      return REPORT_FALLBACK_DATA['sales_performance']!;
  }
}
