import type { ImportSchemaConfig } from '../../../components/import/types';

export const couponImportSchema: ImportSchemaConfig = {
  entityTitle: 'Storefront Discount Coupons & Promo Codes',
  templateFileName: 'erp_coupons_import_template',
  uniqueIdentifierKey: 'code',
  supportsUpsert: true,
  apiEndpoint: '/storefront/coupons/bulk-import',
  columns: [
    {
      key: 'code',
      label: 'Coupon / Promo Code',
      required: true,
      type: 'string',
      sampleValue: 'SAVE20',
      description: 'Customer-facing voucher string (automatically uppercase)',
      aliases: ['code', 'coupon_code', 'promo_code', 'voucher_code', 'coupon', 'voucher'],
    },
    {
      key: 'name',
      label: 'Campaign / Promotion Name',
      required: false,
      type: 'string',
      sampleValue: 'Autumn Flash Sale 20% Off',
      description: 'Internal campaign identifier or title (defaults to code)',
      aliases: ['name', 'title', 'coupon_name', 'description', 'campaign_name'],
    },
    {
      key: 'discount_type',
      label: 'Discount Type',
      required: false,
      type: 'enum',
      options: ['percentage', 'fixed', 'free_shipping'],
      sampleValue: 'percentage',
      description: 'percentage, fixed, or free_shipping (default: percentage)',
      aliases: ['discount_type', 'type', 'calc_type', 'voucher_type'],
    },
    {
      key: 'discount_value',
      label: 'Discount Value',
      required: true,
      type: 'number',
      sampleValue: 20.0,
      description: 'Percentage discount (e.g. 20 for 20%) or flat currency amount (e.g. 50)',
      aliases: ['discount_value', 'discount', 'value', 'amount', 'rate', 'discount_rate'],
    },
    {
      key: 'min_order_amount',
      label: 'Minimum Order Spend',
      required: false,
      type: 'number',
      sampleValue: 500.0,
      description: 'Minimum cart subtotal required to qualify for discount',
      aliases: ['min_order_amount', 'min_spend', 'min_purchase', 'min_order', 'minimum_spend'],
    },
    {
      key: 'max_discount_amount',
      label: 'Maximum Discount Cap',
      required: false,
      type: 'number',
      sampleValue: 200.0,
      description: 'Upper ceiling amount for percentage discounts',
      aliases: ['max_discount_amount', 'max_discount', 'discount_cap', 'cap', 'maximum_discount'],
    },
    {
      key: 'applies_to',
      label: 'Scope / Applies To',
      required: false,
      type: 'enum',
      options: ['order', 'product', 'category', 'shipping'],
      sampleValue: 'order',
      description: 'order, product, category, or shipping (default: order)',
      aliases: ['applies_to', 'scope', 'target', 'applies'],
    },
    {
      key: 'usage_limit_total',
      label: 'Total Global Usage Limit',
      required: false,
      type: 'number',
      sampleValue: 1000,
      description: 'Maximum total redemption count across all customers (empty for unlimited)',
      aliases: ['usage_limit_total', 'usage_limit', 'total_limit', 'max_uses', 'total_redemptions'],
    },
    {
      key: 'usage_limit_per_customer',
      label: 'Per-Customer Usage Limit',
      required: false,
      type: 'number',
      sampleValue: 1,
      description: 'Maximum uses allowed per individual customer (default: 1)',
      aliases: ['usage_limit_per_customer', 'limit_per_user', 'customer_limit', 'per_customer'],
    },
    {
      key: 'starts_at',
      label: 'Valid From (YYYY-MM-DD)',
      required: false,
      type: 'string',
      sampleValue: '2026-09-01',
      description: 'Promotion activation timestamp or date',
      aliases: ['starts_at', 'start_date', 'valid_from', 'from', 'start_at'],
    },
    {
      key: 'ends_at',
      label: 'Valid Until / Expiry (YYYY-MM-DD)',
      required: false,
      type: 'string',
      sampleValue: '2026-10-01',
      description: 'Promotion expiration timestamp or date',
      aliases: ['ends_at', 'end_date', 'expiry_date', 'valid_to', 'to', 'end_at'],
    },
    {
      key: 'is_active',
      label: 'Active Status',
      required: false,
      type: 'boolean',
      sampleValue: true,
      description: 'Whether coupon is immediately enabled for storefront redemption (default: true)',
      aliases: ['is_active', 'active', 'status', 'enabled'],
    },
  ],
};
