import type { ImportSchemaConfig } from '../../../components/import/types';

export const pieceRateLogImportSchema: ImportSchemaConfig = {
  entityTitle: 'Worker Piece-Rate Floor Logs',
  templateFileName: 'erp_piece_rate_logs_import_template',
  uniqueIdentifierKey: 'employee_code',
  supportsUpsert: true,
  apiEndpoint: '/production/worker-entries/bulk-import',
  columns: [
    {
      key: 'employee_code',
      label: 'Employee / Worker Code',
      required: true,
      type: 'string',
      sampleValue: 'EMP-001',
      description: 'Unique worker or technician payroll badge number',
      aliases: ['employee_code', 'employee', 'worker_code', 'worker_id', 'employee_id', 'worker', 'operator_code'],
    },
    {
      key: 'product_sku',
      label: 'Manufactured Product SKU',
      required: true,
      type: 'string',
      sampleValue: 'PRD-RAW-001',
      description: 'SKU code of the item assembled or fabricated',
      aliases: ['product_sku', 'sku', 'product_code', 'product_name', 'product', 'item_code'],
    },
    {
      key: 'batch_code',
      label: 'Production Batch Code',
      required: false,
      type: 'string',
      sampleValue: 'BATCH-2026-001',
      description: 'Associated factory batch run (auto-resolved if empty)',
      aliases: ['batch_code', 'batch_number', 'batch_no', 'batch', 'run_number', 'lot_number'],
    },
    {
      key: 'work_date',
      label: 'Work Log Date (YYYY-MM-DD)',
      required: false,
      type: 'string',
      sampleValue: '2026-09-13',
      description: 'Date work was performed (default: today)',
      aliases: ['work_date', 'date', 'log_date', 'entry_date', 'production_date'],
    },
    {
      key: 'shift_code',
      label: 'Shift Code / Name',
      required: false,
      type: 'string',
      sampleValue: 'MORNING',
      description: 'Operating factory shift code or name',
      aliases: ['shift_code', 'shift', 'shift_name', 'roster_shift'],
    },
    {
      key: 'quantity',
      label: 'Completed / Accepted Quantity',
      required: true,
      type: 'number',
      sampleValue: 120.0,
      description: 'Count or measurement of good units produced',
      aliases: ['quantity', 'qty', 'units_completed', 'completed_quantity', 'good_quantity', 'pieces_produced', 'output_qty'],
    },
    {
      key: 'rework_quantity',
      label: 'Rework Quantity',
      required: false,
      type: 'number',
      sampleValue: 5.0,
      description: 'Units requiring correction or touch-up (default: 0)',
      aliases: ['rework_quantity', 'rework', 'rework_qty', 'pieces_reworked', 'reworked'],
    },
    {
      key: 'rejected_quantity',
      label: 'Rejected / Scrap Quantity',
      required: false,
      type: 'number',
      sampleValue: 2.0,
      description: 'Irreparable scrap or defective units (default: 0)',
      aliases: ['rejected_quantity', 'rejected', 'reject_qty', 'scrap_quantity', 'damaged_quantity', 'scrap'],
    },
    {
      key: 'rate',
      label: 'Piece-Rate Wage ($/unit)',
      required: false,
      type: 'number',
      sampleValue: 15.5,
      description: 'Pre-negotiated compensation per finished good unit',
      aliases: ['rate', 'piece_rate', 'unit_rate', 'rate_per_unit', 'wage_rate'],
    },
    {
      key: 'incentive_amount',
      label: 'Floor Incentive / Bonus',
      required: false,
      type: 'number',
      sampleValue: 50.0,
      description: 'Performance bonus or overtime stipend',
      aliases: ['incentive_amount', 'incentive', 'bonus', 'floor_bonus', 'stipend'],
    },
    {
      key: 'hours_worked',
      label: 'Hours Worked',
      required: false,
      type: 'number',
      sampleValue: 8.0,
      description: 'Total active floor duration in hours',
      aliases: ['hours_worked', 'hours', 'work_hours', 'duration_hours', 'time_spent'],
    },
    {
      key: 'unit_code',
      label: 'Unit of Measure',
      required: false,
      type: 'string',
      sampleValue: 'PCS',
      description: 'Unit code (default: product default unit)',
      aliases: ['unit_code', 'unit', 'uom'],
    },
    {
      key: 'status',
      label: 'Log Verification Status',
      required: false,
      type: 'enum',
      options: ['submitted', 'verified', 'approved', 'rejected'],
      sampleValue: 'submitted',
      description: 'submitted, verified, approved, or rejected (default: submitted)',
      aliases: ['status', 'entry_status', 'state'],
    },
  ],
};
