import type { ImportSchemaConfig } from '../../../components/import/types';

export const productionPlanImportSchema: ImportSchemaConfig = {
  entityTitle: 'Production Plans & Schedules',
  templateFileName: 'erp_production_plans_import_template',
  uniqueIdentifierKey: 'plan_number',
  supportsUpsert: true,
  apiEndpoint: '/production/plans/bulk-import',
  columns: [
    {
      key: 'plan_number',
      label: 'Plan Code / Number',
      required: false,
      type: 'string',
      sampleValue: 'PLAN-2026-09-001',
      description: 'Unique production plan reference number (auto-generated if omitted)',
      aliases: ['plan_number', 'plan_code', 'code', 'plan_no', 'plan_id', 'plan'],
    },
    {
      key: 'plan_date',
      label: 'Planning Date (YYYY-MM-DD)',
      required: false,
      type: 'string',
      sampleValue: '2026-09-15',
      description: 'Formal scheduling/planning date formatted as YYYY-MM-DD (default: today)',
      aliases: ['plan_date', 'date', 'created_date', 'schedule_date'],
    },
    {
      key: 'period_start',
      label: 'Period Start Date (YYYY-MM-DD)',
      required: false,
      type: 'string',
      sampleValue: '2026-09-15',
      description: 'Beginning of manufacturing run window',
      aliases: ['period_start', 'start_date', 'from_date', 'run_start'],
    },
    {
      key: 'period_end',
      label: 'Period End Date (YYYY-MM-DD)',
      required: false,
      type: 'string',
      sampleValue: '2026-10-15',
      description: 'Deadline or closure date of manufacturing cycle',
      aliases: ['period_end', 'end_date', 'to_date', 'run_end'],
    },
    {
      key: 'product_sku',
      label: 'Product SKU / Code',
      required: true,
      type: 'string',
      sampleValue: 'PRD-RAW-001',
      description: 'SKU or unique product code being manufactured',
      aliases: ['product_sku', 'sku', 'product_code', 'product_name', 'product', 'item_code'],
    },
    {
      key: 'planned_quantity',
      label: 'Planned Target Quantity',
      required: true,
      type: 'number',
      sampleValue: 500.0,
      description: 'Scheduled output quantity to produce',
      aliases: ['planned_quantity', 'quantity', 'qty', 'planned_qty', 'target_quantity', 'target_qty', 'target_amount'],
    },
    {
      key: 'unit_code',
      label: 'UOM / Unit Code',
      required: false,
      type: 'string',
      sampleValue: 'PCS',
      description: 'Measurement unit code (e.g. PCS, KG, MTR). Defaults to product standard unit',
      aliases: ['unit_code', 'unit', 'uom', 'unit_name', 'measurement_unit'],
    },
    {
      key: 'scheduled_date',
      label: 'Line Item Scheduled Date',
      required: false,
      type: 'string',
      sampleValue: '2026-09-20',
      description: 'Target completion date for this specific product schedule',
      aliases: ['scheduled_date', 'item_scheduled_date', 'item_date', 'delivery_date'],
    },
    {
      key: 'status',
      label: 'Plan Status',
      required: false,
      type: 'enum',
      options: ['draft', 'approved', 'in_progress', 'completed', 'cancelled'],
      sampleValue: 'draft',
      description: 'draft, approved, in_progress, completed, or cancelled (default: draft)',
      aliases: ['status', 'plan_status', 'state'],
    },
    {
      key: 'notes',
      label: 'Operational Notes & Directives',
      required: false,
      type: 'string',
      sampleValue: 'High-priority export order run for wholesale client',
      aliases: ['notes', 'description', 'remarks', 'comment', 'instructions'],
    },
  ],
};
