<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Modules\Reports\Models\ReportDefinition;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

final class ReportDefinitionsTableSeeder extends Seeder
{
    /**
     * Seed all enterprise report definitions across the 12 core business modules
     * according to Section 39 (Reporting & RMS) of the platform specification.
     */
    public function run(): void
    {
        $reports = [
            // ==========================================
            // 1. PRODUCTION REPORTS
            // ==========================================
            [
                'code' => 'daily_production',
                'name' => 'Daily Production Report',
                'module' => 'production',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Daily output units planned vs actual produced per line and shift.',
                'required_permission' => 'production.view',
            ],
            [
                'code' => 'monthly_production',
                'name' => 'Monthly Production Summary',
                'module' => 'production',
                'category' => 'analytical',
                'tier' => 'live',
                'description' => 'Aggregated monthly production volume, capacity utilization %, and schedule adherence.',
                'required_permission' => 'production.view',
            ],
            [
                'code' => 'production_target_vs_achievement',
                'name' => 'Production Target vs Achievement',
                'module' => 'production',
                'category' => 'analytical',
                'tier' => 'live',
                'description' => 'Comparative variance between factory target goals and actual manufactured output.',
                'required_permission' => 'production.view',
            ],
            [
                'code' => 'production_yield',
                'name' => 'Production Yield & Scrap Analysis',
                'module' => 'production',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Batch-level yield efficiency %, actual vs planned output, and defect rejection count.',
                'required_permission' => 'production.view',
            ],
            [
                'code' => 'total_input_output',
                'name' => 'Total Input vs Output Analysis',
                'module' => 'production',
                'category' => 'analytical',
                'tier' => 'hourly',
                'description' => 'Mass balance ratio of raw material inputs against completed finished goods output.',
                'required_permission' => 'production.view',
            ],
            [
                'code' => 'worker_production',
                'name' => 'Worker Piece-Rate Production Log',
                'module' => 'production',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Line operator individual output logs, hours worked, and earned piece-rate values.',
                'required_permission' => 'production.view',
            ],
            [
                'code' => 'product_wise_production',
                'name' => 'Product-wise Production Analysis',
                'module' => 'production',
                'category' => 'analytical',
                'tier' => 'hourly',
                'description' => 'Manufactured quantities, cycle times, and output volume segmented by product SKU.',
                'required_permission' => 'production.view',
            ],
            [
                'code' => 'factory_wise_production',
                'name' => 'Factory-wise Production Matrix',
                'module' => 'production',
                'category' => 'executive',
                'tier' => 'live',
                'description' => 'Multi-factory comparison of overall manufacturing output, capacity, and active lines.',
                'required_permission' => 'production.view',
            ],
            [
                'code' => 'line_wise_production',
                'name' => 'Line-wise Production & Bottlenecks',
                'module' => 'production',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Assembly line efficiency, hourly run rates (pcs/hr), downtime, and bottlenecks.',
                'required_permission' => 'production.view',
            ],
            [
                'code' => 'shift_wise_production',
                'name' => 'Shift-wise Production & Efficiency',
                'module' => 'production',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Output variance, labor utilization, and efficiency comparing Day vs Night shifts.',
                'required_permission' => 'production.view',
            ],
            [
                'code' => 'production_efficiency',
                'name' => 'Production Efficiency & Cycle Variance',
                'module' => 'production',
                'category' => 'analytical',
                'tier' => 'daily',
                'description' => 'Overall Equipment Effectiveness (OEE) and standard minute value (SMV) variances.',
                'required_permission' => 'production.view',
            ],
            [
                'code' => 'production_wastage_scrap',
                'name' => 'Production Wastage, Rework & Scrap',
                'module' => 'production',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Material wastage logs, rework labor hours, and scrap value write-offs.',
                'required_permission' => 'production.view',
            ],

            // ==========================================
            // 2. INVENTORY & WAREHOUSE REPORTS
            // ==========================================
            [
                'code' => 'stock_valuation',
                'name' => 'Warehouse Stock Valuation & Aging',
                'module' => 'inventory',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'On-hand inventory valued at weighted average cost with FIFO aging brackets.',
                'required_permission' => 'inventory.view',
            ],
            [
                'code' => 'current_stock',
                'name' => 'Current Stock On-Hand & Levels',
                'module' => 'inventory',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Live on-hand physical stock, reserved quantities, and available units per warehouse.',
                'required_permission' => 'inventory.view',
            ],
            [
                'code' => 'stock_ledger',
                'name' => 'Perpetual Stock Ledger',
                'module' => 'inventory',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Chronological audit trail of all inventory receipts, issues, and adjustments.',
                'required_permission' => 'inventory.view',
            ],
            [
                'code' => 'stock_movement',
                'name' => 'Stock Movement & Velocity (In/Out)',
                'module' => 'inventory',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Fast vs slow-moving stock velocity, turnover rates, and movement history.',
                'required_permission' => 'inventory.view',
            ],
            [
                'code' => 'low_stock',
                'name' => 'Low Stock & Reorder Thresholds',
                'module' => 'inventory',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Items approaching or breaching safety stock levels requiring immediate replenishment.',
                'required_permission' => 'inventory.view',
            ],
            [
                'code' => 'out_of_stock',
                'name' => 'Out of Stock & Stockout Impact',
                'module' => 'inventory',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Items with zero available inventory and associated open sales demand.',
                'required_permission' => 'inventory.view',
            ],
            [
                'code' => 'warehouse_stock',
                'name' => 'Warehouse Stock Distribution',
                'module' => 'inventory',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Cross-facility stock distribution across Central Factory, Retail Outlets, and In-Transit.',
                'required_permission' => 'inventory.view',
            ],
            [
                'code' => 'warehouse_transfer',
                'name' => 'Warehouse Inter-Transfer Log',
                'module' => 'inventory',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Completed, in-transit, and pending stock transfer notes between warehouse facilities.',
                'required_permission' => 'inventory.view',
            ],
            [
                'code' => 'raw_material_stock',
                'name' => 'Raw Material Stock Valuation',
                'module' => 'inventory',
                'category' => 'financial',
                'tier' => 'hourly',
                'description' => 'Valuation of fabrics, trims, chemicals, and packaging materials on hand.',
                'required_permission' => 'inventory.view',
            ],
            [
                'code' => 'finished_goods_stock',
                'name' => 'Finished Goods Inventory Status',
                'module' => 'inventory',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Commercial valuation of finished apparel ready for wholesale and retail dispatch.',
                'required_permission' => 'inventory.view',
            ],
            [
                'code' => 'damaged_stock',
                'name' => 'Damaged & Written-off Stock',
                'module' => 'inventory',
                'category' => 'operational',
                'tier' => 'daily',
                'description' => 'Damaged items logged from transit, factory floor, or warehouse accidents.',
                'required_permission' => 'inventory.view',
            ],

            // ==========================================
            // 3. PURCHASE & PROCUREMENT REPORTS
            // ==========================================
            [
                'code' => 'purchase_summary',
                'name' => 'Purchase Order (PO) Summary',
                'module' => 'purchasing',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Overview of open, partially received, closed, and cancelled purchase orders.',
                'required_permission' => 'purchasing.view',
            ],
            [
                'code' => 'purchase_details',
                'name' => 'Purchase Details & GRN Log',
                'module' => 'purchasing',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Goods Receipt Notes (GRN) with received quantities, accepted goods, and variances.',
                'required_permission' => 'purchasing.view',
            ],
            [
                'code' => 'supplier_purchase',
                'name' => 'Supplier-wise Purchase Analysis',
                'module' => 'purchasing',
                'category' => 'analytical',
                'tier' => 'hourly',
                'description' => 'Procurement volume, financial spend, and vendor fulfillment lead time compliance.',
                'required_permission' => 'purchasing.view',
            ],
            [
                'code' => 'product_purchase',
                'name' => 'Raw Material Purchase Price Trends',
                'module' => 'purchasing',
                'category' => 'analytical',
                'tier' => 'daily',
                'description' => 'Historical cost fluctuations per kilogram/meter across supplier quotes over time.',
                'required_permission' => 'purchasing.view',
            ],
            [
                'code' => 'purchase_return',
                'name' => 'Purchase Returns & Debit Notes',
                'module' => 'purchasing',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Returned defective vendor materials and associated debit adjustments.',
                'required_permission' => 'purchasing.view',
            ],
            [
                'code' => 'supplier_due',
                'name' => 'Supplier Payables & Aging Ledger',
                'module' => 'purchasing',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Outstanding supplier balances categorized by 0-30, 31-60, 61-90, 90+ days aging.',
                'required_permission' => 'purchasing.view',
            ],
            [
                'code' => 'supplier_payment_history',
                'name' => 'Supplier Payment Disbursement History',
                'module' => 'purchasing',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Chronological record of vendor payments made via bank transfer, check, and cash.',
                'required_permission' => 'purchasing.view',
            ],

            // ==========================================
            // 4. SALES & POS REPORTS
            // ==========================================
            [
                'code' => 'daily_sales',
                'name' => 'Daily Sales & Revenue Ledger',
                'module' => 'sales',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Daily order volume, gross receipts, applied discounts, and net collected revenue.',
                'required_permission' => 'sales.view',
            ],
            [
                'code' => 'monthly_sales',
                'name' => 'Monthly Sales Velocity & Trends',
                'module' => 'sales',
                'category' => 'analytical',
                'tier' => 'daily',
                'description' => 'Month-over-month sales trends, seasonal velocity, and average order value (AOV).',
                'required_permission' => 'sales.view',
            ],
            [
                'code' => 'product_sales',
                'name' => 'Product-wise Sales Analysis',
                'module' => 'sales',
                'category' => 'analytical',
                'tier' => 'hourly',
                'description' => 'Best-selling SKUs, inventory turnover speed, and revenue per product style.',
                'required_permission' => 'sales.view',
            ],
            [
                'code' => 'customer_sales',
                'name' => 'Customer & Client-wise Sales Volume',
                'module' => 'sales',
                'category' => 'analytical',
                'tier' => 'daily',
                'description' => 'B2B institutional client purchasing volume, credit terms, and order frequency.',
                'required_permission' => 'sales.view',
            ],
            [
                'code' => 'salesman_sales',
                'name' => 'Salesman Sales Attribution',
                'module' => 'sales',
                'category' => 'analytical',
                'tier' => 'live',
                'description' => 'Revenue directly attributed to assigned showroom and field sales representatives.',
                'required_permission' => 'sales.view',
            ],
            [
                'code' => 'sales_performance',
                'name' => 'Channel Sales & Revenue Ledger',
                'module' => 'sales',
                'category' => 'analytical',
                'tier' => 'live',
                'description' => 'Order volume, gross sales revenue, applied discounts, and payment settlement breakdown by channel.',
                'required_permission' => 'sales.view',
            ],
            [
                'code' => 'b2b_sales',
                'name' => 'B2B Wholesale Sales Ledger',
                'module' => 'sales',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Bulk wholesale order volume, invoice balances, and institutional payment terms.',
                'required_permission' => 'sales.view',
            ],
            [
                'code' => 'b2c_sales',
                'name' => 'B2C & Online Storefront Sales',
                'module' => 'sales',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Online customer orders, storefront conversion rates, and digital payments.',
                'required_permission' => 'sales.view',
            ],
            [
                'code' => 'pos_counter_sales',
                'name' => 'POS Counter Shift & Tender Reconciliation',
                'module' => 'sales',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'POS counter shift opening cash, cash sales, card payments, mobile banking, and variance.',
                'required_permission' => 'pos.view',
            ],
            [
                'code' => 'sales_return',
                'name' => 'Sales Returns & Credit Notes',
                'module' => 'sales',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Customer return items, return reasons, refund types, and restocked units.',
                'required_permission' => 'sales.view',
            ],

            // ==========================================
            // 5. PROFITABILITY REPORTS
            // ==========================================
            [
                'code' => 'invoice_profit',
                'name' => 'Invoice-wise Gross Profit Analysis',
                'module' => 'profit',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Individual commercial invoices analyzed by sales price minus COGS for gross profit margin.',
                'required_permission' => 'finance.view',
            ],
            [
                'code' => 'product_profit',
                'name' => 'Product-wise Profit & Gross Margin %',
                'module' => 'profit',
                'category' => 'analytical',
                'tier' => 'hourly',
                'description' => 'Gross margin ranking and contribution percentage calculated across product catalog.',
                'required_permission' => 'finance.view',
            ],
            [
                'code' => 'salesman_profitability',
                'name' => 'Salesman Profitability Contribution',
                'module' => 'profit',
                'category' => 'analytical',
                'tier' => 'daily',
                'description' => 'Net profit generated per salesperson after subtracting product cost and commissions.',
                'required_permission' => 'sales.view',
            ],
            [
                'code' => 'daily_profit',
                'name' => 'Daily Gross Profit Ledger',
                'module' => 'profit',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Daily gross profit totals comparing billed revenue with estimated goods cost.',
                'required_permission' => 'finance.view',
            ],
            [
                'code' => 'monthly_profit',
                'name' => 'Monthly Profit & Loss Summary',
                'module' => 'profit',
                'category' => 'executive',
                'tier' => 'daily',
                'description' => 'Comprehensive monthly bottom-line summary comparing revenues, COGS, and factory expenses.',
                'required_permission' => 'finance.view',
            ],

            // ==========================================
            // 6. CRM & LEADS REPORTS
            // ==========================================
            [
                'code' => 'lead_summary',
                'name' => 'Commercial Lead Pipeline Summary',
                'module' => 'crm',
                'category' => 'analytical',
                'tier' => 'live',
                'description' => 'Total leads across pipeline stages: New, Contacted, Qualified, Follow-up, Converted, Lost.',
                'required_permission' => 'crm.view',
            ],
            [
                'code' => 'salesman_leads',
                'name' => 'Salesman Lead Allocation & Workload',
                'module' => 'crm',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Active workload distribution and assigned leads per sales representative.',
                'required_permission' => 'crm.view',
            ],
            [
                'code' => 'lead_status_distribution',
                'name' => 'Lead Status & Stage Distribution',
                'module' => 'crm',
                'category' => 'analytical',
                'tier' => 'live',
                'description' => 'Distribution breakdown of active customer inquiries across lifecycle stages.',
                'required_permission' => 'crm.view',
            ],
            [
                'code' => 'fake_leads_audit',
                'name' => 'Fake & Invalid Lead Verification Audit',
                'module' => 'crm',
                'category' => 'compliance',
                'tier' => 'live',
                'description' => 'Audit log of unverified, unreachable, or flagged fraudulent customer inquiries.',
                'required_permission' => 'crm.view',
            ],
            [
                'code' => 'converted_leads',
                'name' => 'Converted Leads & Deal Value',
                'module' => 'crm',
                'category' => 'analytical',
                'tier' => 'live',
                'description' => 'Successful conversions resulting in confirmed invoices and sales revenue.',
                'required_permission' => 'crm.view',
            ],
            [
                'code' => 'conversion_rate_source',
                'name' => 'Lead Conversion Rate by Source',
                'module' => 'crm',
                'category' => 'analytical',
                'tier' => 'daily',
                'description' => 'Conversion efficiency calculated across Facebook, Storefront, WhatsApp, and Walk-ins.',
                'required_permission' => 'crm.view',
            ],
            [
                'code' => 'lost_leads_analysis',
                'name' => 'Lost Leads & Rejection Analysis',
                'module' => 'crm',
                'category' => 'analytical',
                'tier' => 'daily',
                'description' => 'Analysis of reasons behind lost opportunities (pricing, stock availability, competitor).',
                'required_permission' => 'crm.view',
            ],

            // ==========================================
            // 7. SALESMEN MANAGEMENT REPORTS
            // ==========================================
            [
                'code' => 'salesman_quota_achievement',
                'name' => 'Salesman Monthly Quota vs Achievement',
                'module' => 'salesmen',
                'category' => 'executive',
                'tier' => 'live',
                'description' => 'Assigned monthly sales targets (৳) vs achieved revenue and target completion percentage.',
                'required_permission' => 'sales.view',
            ],
            [
                'code' => 'salesman_remaining_target',
                'name' => 'Salesman Remaining Target & Quota Shortfall',
                'module' => 'salesmen',
                'category' => 'analytical',
                'tier' => 'live',
                'description' => 'Pending sales shortfall required for each salesman to meet monthly minimum quotas.',
                'required_permission' => 'sales.view',
            ],
            [
                'code' => 'salesman_profit_contribution',
                'name' => 'Salesman Net Profit Contribution',
                'module' => 'salesmen',
                'category' => 'financial',
                'tier' => 'daily',
                'description' => 'Actual gross margin and profit delivered by each sales agent beyond revenue.',
                'required_permission' => 'sales.view',
            ],
            [
                'code' => 'salesman_incentive_accrual',
                'name' => 'Salesman Tiered Incentive Accrual',
                'module' => 'salesmen',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Tiered commission calculations, approved bonuses, and pending incentive disbursements.',
                'required_permission' => 'sales.view',
            ],
            [
                'code' => 'salesman_leaderboard',
                'name' => 'Sales Representative Performance Leaderboard',
                'module' => 'salesmen',
                'category' => 'analytical',
                'tier' => 'live',
                'description' => 'Ranked performance metrics across sales reps by conversion rate, profit, and volume.',
                'required_permission' => 'sales.view',
            ],

            // ==========================================
            // 8. DELIVERY & LOGISTICS REPORTS
            // ==========================================
            [
                'code' => 'pending_deliveries',
                'name' => 'Pending Deliveries & Dispatch Queue',
                'module' => 'delivery',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Parcels packaged and staged for courier pickup or vehicle loading.',
                'required_permission' => 'delivery.view',
            ],
            [
                'code' => 'delivered_orders',
                'name' => 'Delivered Shipments & POD Log',
                'module' => 'delivery',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Successfully completed shipments with Proof of Delivery (POD) confirmations.',
                'required_permission' => 'delivery.view',
            ],
            [
                'code' => 'returned_orders',
                'name' => 'Returned (RTO) Consignments',
                'module' => 'delivery',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Return-to-origin packages, failed delivery attempts, and customer rejection logs.',
                'required_permission' => 'delivery.view',
            ],
            [
                'code' => 'cancelled_deliveries',
                'name' => 'Cancelled Delivery Dispatches',
                'module' => 'delivery',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Orders cancelled after consignment creation and returned to warehouse shelves.',
                'required_permission' => 'delivery.view',
            ],
            [
                'code' => 'courier_performance',
                'name' => 'Courier Performance (Pathao/Steadfast/In-house)',
                'module' => 'delivery',
                'category' => 'analytical',
                'tier' => 'daily',
                'description' => 'Courier success rate %, average delivery transit time, and SLA performance.',
                'required_permission' => 'delivery.view',
            ],
            [
                'code' => 'cod_reconciliation',
                'name' => 'Cash On Delivery (COD) Remittance & Settlement',
                'module' => 'delivery',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Courier collected cash reconciliation vs actual bank deposits received.',
                'required_permission' => 'delivery.view',
            ],
            [
                'code' => 'delivery_sla_history',
                'name' => 'Delivery SLA & Transit Time History',
                'module' => 'delivery',
                'category' => 'analytical',
                'tier' => 'daily',
                'description' => 'Historical delivery duration tracking across Dhaka Metro vs Divisional areas.',
                'required_permission' => 'delivery.view',
            ],

            // ==========================================
            // 9. HR & WORKFORCE REPORTS
            // ==========================================
            [
                'code' => 'employee_directory',
                'name' => 'Employee Directory & Workforce Distribution',
                'module' => 'hr',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Headcount distribution across Factory Lines, Sales, Logistics, and Administration.',
                'required_permission' => 'hr.view',
            ],
            [
                'code' => 'daily_attendance',
                'name' => 'Daily & Monthly Attendance & Punctuality',
                'module' => 'hr',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Daily check-in, late arrival records, early departures, and approved leave days.',
                'required_permission' => 'hr.view',
            ],
            [
                'code' => 'worker_piece_rate_summary',
                'name' => 'Worker Piece-Rate Production Log',
                'module' => 'hr',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Production worker piece-rate units completed, base pay, and piece bonus accrual.',
                'required_permission' => 'hr.view',
            ],
            [
                'code' => 'payroll_summary',
                'name' => 'Disbursed Payroll Register & Net Pay',
                'module' => 'hr',
                'category' => 'compliance',
                'tier' => 'live',
                'description' => 'Aggregated gross earnings, piece-rate bonuses, deductions, and net payouts per employee department.',
                'required_permission' => 'hr.view',
            ],
            [
                'code' => 'sales_commission_payout',
                'name' => 'Sales Commission & Incentive Payouts',
                'module' => 'hr',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Approved commercial sales incentives transferred to payroll disbursement queues.',
                'required_permission' => 'hr.view',
            ],

            // ==========================================
            // 10. FINANCE & ACCOUNTING REPORTS
            // ==========================================
            [
                'code' => 'gl_summary',
                'name' => 'General Ledger Summary Trial Balance',
                'module' => 'finance',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Debit and credit balance reconciliation across all active asset, liability, equity, income, and expense accounts.',
                'required_permission' => 'finance.view',
            ],
            [
                'code' => 'income_statement',
                'name' => 'Income & Profit/Loss Statement',
                'module' => 'finance',
                'category' => 'financial',
                'tier' => 'daily',
                'description' => 'Operating revenues, cost of sales, operating expenditures, and net income.',
                'required_permission' => 'finance.view',
            ],
            [
                'code' => 'operating_expenses',
                'name' => 'Operating Expense Breakdown by Category',
                'module' => 'finance',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Factory overhead, power/utilities, logistics fees, rent, and administrative spend.',
                'required_permission' => 'finance.view',
            ],
            [
                'code' => 'customer_ar_aging',
                'name' => 'Customer Receivables (AR) Aging (0-90+ Days)',
                'module' => 'finance',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Outstanding B2B trade receivables categorized by current, 30, 60, and 90+ days overdue.',
                'required_permission' => 'finance.view',
            ],
            [
                'code' => 'supplier_ap_aging',
                'name' => 'Supplier Payables (AP) Aging',
                'module' => 'finance',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Vendor bills due for settlement with payment terms and aging breakdown.',
                'required_permission' => 'finance.view',
            ],
            [
                'code' => 'cash_bank_ledger',
                'name' => 'Cash & Bank Accounts Ledger',
                'module' => 'finance',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Balances across all company bank accounts, petty cash registers, and payment gateways.',
                'required_permission' => 'finance.view',
            ],
            [
                'code' => 'payment_method_summary',
                'name' => 'Payment Method Tender Summary',
                'module' => 'finance',
                'category' => 'financial',
                'tier' => 'live',
                'description' => 'Aggregated inflows categorized by Cash, POS Card, Bank EFT, bKash, and Nagad.',
                'required_permission' => 'finance.view',
            ],

            // ==========================================
            // 11. ASSET MANAGEMENT REPORTS
            // ==========================================
            [
                'code' => 'fixed_asset_register',
                'name' => 'Fixed Asset Register & Inventory',
                'module' => 'assets',
                'category' => 'compliance',
                'tier' => 'live',
                'description' => 'Comprehensive register of factory machinery, cutting tables, vehicles, and IT equipment.',
                'required_permission' => 'assets.view',
            ],
            [
                'code' => 'asset_valuation_nbv',
                'name' => 'Asset Valuation & Net Book Value (NBV)',
                'module' => 'assets',
                'category' => 'financial',
                'tier' => 'daily',
                'description' => 'Asset acquisition cost, cumulative depreciation, and current book valuation.',
                'required_permission' => 'assets.view',
            ],
            [
                'code' => 'assigned_assets',
                'name' => 'Assigned Assets by Employee & Line',
                'module' => 'assets',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Assets checked out to specific factory assembly lines, drivers, and supervisors.',
                'required_permission' => 'assets.view',
            ],
            [
                'code' => 'asset_maintenance_log',
                'name' => 'Asset Maintenance, Repairs & Downtime',
                'module' => 'assets',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Preventive maintenance history, emergency breakdown repairs, and parts replacement.',
                'required_permission' => 'assets.view',
            ],
            [
                'code' => 'asset_disposal_history',
                'name' => 'Asset Disposal, Salvage & Write-off History',
                'module' => 'assets',
                'category' => 'compliance',
                'tier' => 'daily',
                'description' => 'Retired equipment, salvage amounts recovered, and scrap write-offs.',
                'required_permission' => 'assets.view',
            ],

            // ==========================================
            // 12. QC & AUDIT COMPLIANCE REPORTS
            // ==========================================
            [
                'code' => 'qc_inspection_ratio',
                'name' => 'QC Inspection Pass / Fail Ratios',
                'module' => 'qc',
                'category' => 'compliance',
                'tier' => 'live',
                'description' => 'Quality pass rates and defect percentage evaluated against AQL 2.5 standards.',
                'required_permission' => 'qc.view',
            ],
            [
                'code' => 'defect_categorization',
                'name' => 'Defect Categorization (Critical/Major/Minor)',
                'module' => 'qc',
                'category' => 'operational',
                'tier' => 'live',
                'description' => 'Categorization of stitching flaws, oil stains, measurement faults, and fabric runs.',
                'required_permission' => 'qc.view',
            ],
            [
                'code' => 'compliance_audit_trail',
                'name' => 'System Compliance & Transaction Audit Trail',
                'module' => 'qc',
                'category' => 'compliance',
                'tier' => 'live',
                'description' => 'Security and financial audit trail of critical operational actions and adjustments.',
                'required_permission' => 'audit.view',
            ],
        ];

        foreach ($reports as $r) {
            ReportDefinition::updateOrCreate(
                [
                    'tenant_id' => 1,
                    'code' => $r['code'],
                ],
                [
                    'uuid' => (string) Str::uuid(),
                    'name' => $r['name'],
                    'module' => $r['module'],
                    'category' => $r['category'],
                    'description' => $r['description'],
                    'required_permission' => $r['required_permission'],
                    'supports_export' => true,
                    'tier' => $r['tier'],
                    'is_active' => true,
                ]
            );
        }
    }
}
