import React from 'react';
import {
  BadgePercent,
  Sparkles,
  ShieldAlert,
  Truck,
  CheckCircle2,
} from 'lucide-react';
import { Badge } from '../../../../components/ui/Badge';

interface CommercialTermsSimulatorProps {
  defaultPaymentTerms?: string;
  creditLimitAction?: string;
  maxCommercialDiscountPercent?: number | string;
  invoiceOverdueGraceDays?: number | string;
  autoGenerateDelivery?: boolean | string;
}

export const CommercialTermsSimulator: React.FC<CommercialTermsSimulatorProps> = ({
  defaultPaymentTerms = 'net_30',
  creditLimitAction = 'block_order',
  maxCommercialDiscountPercent = 15,
  invoiceOverdueGraceDays = 7,
  autoGenerateDelivery = true,
}) => {
  const discountCap = Number(maxCommercialDiscountPercent) || 15;
  const graceDays = Number(invoiceOverdueGraceDays) || 7;
  const isAutoDelivery = autoGenerateDelivery === true || autoGenerateDelivery === '1' || autoGenerateDelivery === 'true';

  return (
    <div className="rounded-xl border border-default bg-surface-sunken/60 overflow-hidden space-y-0 transition-all">
      {/* Top Bar */}
      <div className="px-4 py-3 bg-surface border-b border-default flex flex-wrap items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <div className="size-6 rounded-lg bg-primary/10 text-primary flex items-center justify-center shrink-0">
            <Sparkles className="size-3.5" />
          </div>
          <div>
            <span className="text-xs font-bold text-default block">
              Commercial Credit Terms &amp; Dispatch Governance Simulator
            </span>
            <span className="text-2xs text-muted block">
              Customer credit limit enforcement, discount thresholds, and automated delivery challan workflows
            </span>
          </div>
        </div>

        <Badge tone="primary-subtle" className="text-2xs uppercase font-mono">
          {defaultPaymentTerms.replace(/_/g, ' ')}
        </Badge>
      </div>

      {/* Simulator Content Area */}
      <div className="p-4 space-y-3">
        {/* Credit Limit & Discount Caps */}
        <div className="p-3.5 rounded-xl bg-surface border border-default space-y-2.5">
          <div className="flex items-center justify-between">
            <span className="text-2xs font-bold uppercase tracking-wider text-muted flex items-center gap-1.5">
              <BadgePercent className="size-3 text-primary" />
              Customer Credit Safeguard &amp; Margin Ceiling
            </span>
            <span className="text-2xs font-mono text-muted">Account: ACME Distributors</span>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
            <div className="p-2.5 rounded-lg bg-surface-sunken border border-default space-y-1">
              <span className="text-2xs text-muted block">Breach Action on Limit Exceeded</span>
              <div className="flex items-center gap-1.5">
                <ShieldAlert className="size-3.5 text-warning" />
                <span className="text-xs font-bold text-default capitalize">
                  {creditLimitAction.replace(/_/g, ' ')}
                </span>
              </div>
              <span className="text-2xs text-muted block">
                {creditLimitAction === 'block_order'
                  ? 'Orders are automatically halted until overdue payments are cleared.'
                  : 'Orders require executive management exception signoff.'}
              </span>
            </div>

            <div className="p-2.5 rounded-lg bg-surface-sunken border border-default space-y-1">
              <span className="text-2xs text-muted block">Rep Max Discount Ceiling</span>
              <span className="font-mono text-sm font-bold text-primary block">
                Up to {discountCap}% Max
              </span>
              <span className="text-2xs text-muted block">
                Discounts beyond {discountCap}% require commercial director approval.
              </span>
            </div>
          </div>
        </div>

        {/* Grace Period & Delivery Challan Automation */}
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          <div className="p-3 rounded-lg bg-surface border border-default space-y-1">
            <span className="text-2xs text-muted block uppercase tracking-wider font-medium">
              Overdue Aging Grace Window
            </span>
            <div className="font-mono text-xs font-bold text-default">
              +{graceDays} Days Past Due Date
            </div>
            <span className="text-2xs text-muted block">
              Interest or supply hold alerts trigger after day {graceDays}.
            </span>
          </div>

          <div className="p-3 rounded-lg bg-surface border border-default space-y-1">
            <span className="text-2xs text-muted block uppercase tracking-wider font-medium">
              Automatic Challan Generation
            </span>
            <div className="flex items-center gap-1.5">
              <Truck className="size-3.5 text-success" />
              <span className="text-xs font-bold text-default">
                {isAutoDelivery ? 'Instant Challan Creation' : 'Manual Dispatch Trigger'}
              </span>
            </div>
            <span className="text-2xs text-muted flex items-center gap-1">
              <CheckCircle2 className="size-3 text-success" />
              Challan auto-drafted immediately upon posting a commercial invoice
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};
